development:
  adapter: mysql2
  database:
  username:
  password:
  encoding: utf8
  host: localhost
  port: 3306
  reconnect: true
  pool: 5

development_analysis:
  adapter: mysql2
  database:
  username:
  password:
  encoding: utf8
  host: localhost
  port: 3306
  reconnect: true
  pool: 5

production:
  adapter: mysql2
  database:
  username:
  password:
  encoding: utf8
  host: localhost
  port: 3306
  reconnect: true
  pool: 5

production_analysis:
  adapter: mysql2
  database:
  username:
  password:
  encoding: utf8
  host: localhost
  port: 3306
  reconnect: true
  pool: 5
