class CreateSqlViews < ActiveRecord::Migration
  def up
      execute "drop view if exists `president2013s - invalid ballots 0-1`"
      execute "drop view if exists `president2013s - invalid ballots 1-3`"
      execute "drop view if exists `president2013s - invalid ballots 3-5`"
      execute "drop view if exists `president2013s - invalid ballots >5`"
      execute "drop view if exists `president2013s - vpm 8-12>2`"
      execute "drop view if exists `president2013s - vpm 12-17>2`"
      execute "drop view if exists `president2013s - vpm 17-20>2`"
      execute "drop view if exists `president2013s - country`"
      execute "drop view if exists `president2013s - districts`"
      execute "drop view if exists `president2013s - precincts`"
      execute "drop view if exists `president2013s - region`"
      execute "drop view if exists `president2013s - tbilisi district`"
      execute "drop view if exists `president2013s - tbilisi precincts`"
      execute "drop view if exists `president2013s - csv`"
  
    execute "create view `president2013s - invalid ballots 0-1` as
      select `raw`.`region` AS `region`,
      `raw`.`district_id` AS `district_id`,
      `raw`.`precinct_id` AS `precinct_id`,
      count(0) AS `num_invalid_ballots` from `president2013s` `raw` where (((100 * (`raw`.`num_invalid_votes` / `raw`.`num_votes`)) >= 0) and ((100 * (`raw`.`num_invalid_votes` / `raw`.`num_votes`)) < 1)) group by `raw`.`region`,
      `raw`.`district_id`,
      `raw`.`precinct_id`"

      execute "create view `president2013s - invalid ballots 1-3` as
      select `raw`.`region` AS `region`,
      `raw`.`district_id` AS `district_id`,
      `raw`.`precinct_id` AS `precinct_id`,
      count(0) AS `num_invalid_ballots` from `president2013s` `raw` where (((100 * (`raw`.`num_invalid_votes` / `raw`.`num_votes`)) >= 1) and ((100 * (`raw`.`num_invalid_votes` / `raw`.`num_votes`)) < 3)) group by `raw`.`region`,
      `raw`.`district_id`,
      `raw`.`precinct_id`"

      execute "create view `president2013s - invalid ballots 3-5` as
      select `raw`.`region` AS `region`,
      `raw`.`district_id` AS `district_id`,
      `raw`.`precinct_id` AS `precinct_id`,
      count(0) AS `num_invalid_ballots` from `president2013s` `raw` where (((100 * (`raw`.`num_invalid_votes` / `raw`.`num_votes`)) >= 3) and ((100 * (`raw`.`num_invalid_votes` / `raw`.`num_votes`)) < 5)) group by `raw`.`region`,
      `raw`.`district_id`,
      `raw`.`precinct_id`"

      execute "create view `president2013s - invalid ballots >5` as
      select `raw`.`region` AS `region`,
      `raw`.`district_id` AS `district_id`,
      `raw`.`precinct_id` AS `precinct_id`,
      count(0) AS `num_invalid_ballots` from `president2013s` `raw` where ((100 * (`raw`.`num_invalid_votes` / `raw`.`num_votes`)) >= 5) group by `raw`.`region`,
      `raw`.`district_id`,
      `raw`.`precinct_id`"

      execute "create view `president2013s - vpm 8-12>2` as
      select `president2013s`.`region` AS `region`,
      `president2013s`.`district_id` AS `district_id`,
      `president2013s`.`precinct_id` AS `precinct_id`,
      count(0) AS `vpm > 2` from `president2013s` where ((`president2013s`.`num_at_12` / 240) > 2) group by `president2013s`.`region`,
      `president2013s`.`district_id`,
      `president2013s`.`precinct_id`"

      execute "create view `president2013s - vpm 12-17>2` as
      select `president2013s`.`region` AS `region`,
      `president2013s`.`district_id` AS `district_id`,
      `president2013s`.`precinct_id` AS `precinct_id`,
      count(0) AS `vpm > 2` from `president2013s` where (((`president2013s`.`num_at_17` - `president2013s`.`num_at_12`) / 300) > 2) group by `president2013s`.`region`,
      `president2013s`.`district_id`,
      `president2013s`.`precinct_id`"

      execute "create view `president2013s - vpm 17-20>2` as
      select `president2013s`.`region` AS `region`,
      `president2013s`.`district_id` AS `district_id`,
      `president2013s`.`precinct_id` AS `precinct_id`,
      count(0) AS `vpm > 2` from `president2013s` where (((`president2013s`.`num_votes` - `president2013s`.`num_at_17`) / 180) > 2) group by `president2013s`.`region`,
      `president2013s`.`district_id`,
      `president2013s`.`precinct_id`"


      execute "create view `president2013s - country` as
      select sum(`raw`.`num_possible_voters`) AS `possible voters`,
      sum(`raw`.`num_votes`) AS `total ballots cast`,
      sum(`raw`.`num_valid_votes`) AS `total valid ballots cast`,
      ifnull(sum(`invalid_ballots_01`.`num_invalid_ballots`),
      0) AS `num invalid ballots from 0-1%`,
      ifnull(sum(`invalid_ballots_13`.`num_invalid_ballots`),
      0) AS `num invalid ballots from 1-3%`,
      ifnull(sum(`invalid_ballots_35`.`num_invalid_ballots`),
      0) AS `num invalid ballots from 3-5%`,
      ifnull(sum(`invalid_ballots_>5`.`num_invalid_ballots`),
      0) AS `num invalid ballots >5%`,
      (100 * (sum(`raw`.`num_valid_votes`) / sum(`raw`.`num_possible_voters`))) AS `percent voters voting`,
      sum(`raw`.`logic_check_fail`) AS `num precincts logic fail`,
      (100 * (sum(`raw`.`logic_check_fail`) / count(0))) AS `percent precincts logic fail`,
      (sum(`raw`.`logic_check_difference`) / sum(`raw`.`logic_check_fail`)) AS `avg precinct logic fail difference`,
      sum(`raw`.`more_ballots_than_votes_flag`) AS `num precincts more ballots than votes`,
      (100 * (sum(`raw`.`more_ballots_than_votes_flag`) / count(0))) AS `percent precincts more ballots than votes`,
      (sum(`raw`.`more_ballots_than_votes`) / sum(`raw`.`more_ballots_than_votes_flag`)) AS `avg precinct difference more ballots than votes`,
      sum(`raw`.`more_votes_than_ballots_flag`) AS `num precincts more votes than ballots`,
      (100 * (sum(`raw`.`more_votes_than_ballots_flag`) / count(0))) AS `percent precincts more votes than ballots`,
      (sum(`raw`.`more_votes_than_ballots`) / sum(`raw`.`more_votes_than_ballots_flag`)) AS `avg precinct difference more votes than ballots`,
      sum(`raw`.`num_at_12`) AS `votes 8-12`,
      sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) AS `votes 12-17`,
      sum((`raw`.`num_votes` - `raw`.`num_at_17`)) AS `votes 17-20`,
      (sum(`raw`.`num_at_12`) / count(0)) AS `avg votes/precinct 8-12`,
      (sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) / count(0)) AS `avg votes/precinct 12-17`,
      (sum((`raw`.`num_votes` - `raw`.`num_at_17`)) / count(0)) AS `avg votes/precinct 17-20`,
      (sum(`raw`.`num_at_12`) / 240) AS `vpm 8-12`,
      (sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) / 180) AS `vpm 12-17`,
      (sum((`raw`.`num_votes` - `raw`.`num_at_17`)) / 300) AS `vpm 17-20`,
      ((sum(`raw`.`num_at_12`) / 240) / count(0)) AS `avg vpm/precinct 8-12`,
      ((sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) / 180) / count(0)) AS `avg vpm/precinct 12-17`,
      ((sum((`raw`.`num_votes` - `raw`.`num_at_17`)) / 200) / count(0)) AS `avg vpm/precinct 17-20`,
      ifnull(sum(`vpm1`.`vpm > 2`),
      0) AS `num precincts vpm 8-12 > 2`,
      ifnull(sum(`vpm2`.`vpm > 2`),
      0) AS `num precincts vpm 12-17 > 2`,
      ifnull(sum(`vpm3`.`vpm > 2`),
      0) AS `num precincts vpm 17-20 > 2`,
      ((ifnull(sum(`vpm1`.`vpm > 2`),
      0) + ifnull(sum(`vpm2`.`vpm > 2`),
      0)) + ifnull(sum(`vpm3`.`vpm > 2`),
      0)) AS `num precincts vpm > 2`,
      `precinct_count`.`num_precincts` AS `num_precincts_possible`,
      count(`raw`.`precinct_id`) AS `num_precincts_reported_number`,
      ((100 * count(`raw`.`precinct_id`)) / `precinct_count`.`num_precincts`) AS `num_precincts_reported_percent`,
      sum(`raw`.`1 - Tamaz Bibiluri`) AS `1 - Tamaz Bibiluri count`,
      (100 * (sum(`raw`.`1 - Tamaz Bibiluri`) / sum(`raw`.`num_valid_votes`))) AS `1 - Tamaz Bibiluri`,
      sum(`raw`.`2 - Giorgi Liluashvili`) AS `2 - Giorgi Liluashvili count`,
      (100 * (sum(`raw`.`2 - Giorgi Liluashvili`) / sum(`raw`.`num_valid_votes`))) AS `2 - Giorgi Liluashvili`,
      sum(`raw`.`3 - Sergo Javakhidze`) AS `3 - Sergo Javakhidze count`,
      (100 * (sum(`raw`.`3 - Sergo Javakhidze`) / sum(`raw`.`num_valid_votes`))) AS `3 - Sergo Javakhidze`,
      sum(`raw`.`4 - Koba Davitashvili`) AS `4 - Koba Davitashvili count`,
      (100 * (sum(`raw`.`4 - Koba Davitashvili`) / sum(`raw`.`num_valid_votes`))) AS `4 - Koba Davitashvili`,
      sum(`raw`.`5 - Davit Bakradze`) AS `5 - Davit Bakradze count`,
      (100 * (sum(`raw`.`5 - Davit Bakradze`) / sum(`raw`.`num_valid_votes`))) AS `5 - Davit Bakradze`,
      sum(`raw`.`6 - Akaki Asatiani`) AS `6 - Akaki Asatiani count`,
      (100 * (sum(`raw`.`6 - Akaki Asatiani`) / sum(`raw`.`num_valid_votes`))) AS `6 - Akaki Asatiani`,
      sum(`raw`.`7 - Nino Chanishvili`) AS `7 - Nino Chanishvili count`,
      (100 * (sum(`raw`.`7 - Nino Chanishvili`) / sum(`raw`.`num_valid_votes`))) AS `7 - Nino Chanishvili`,
      sum(`raw`.`8 - Teimuraz Bobokhidze`) AS `8 - Teimuraz Bobokhidze count`,
      (100 * (sum(`raw`.`8 - Teimuraz Bobokhidze`) / sum(`raw`.`num_valid_votes`))) AS `8 - Teimuraz Bobokhidze`,
      sum(`raw`.`9 - Shalva Natelashvili`) AS `9 - Shalva Natelashvili count`,
      (100 * (sum(`raw`.`9 - Shalva Natelashvili`) / sum(`raw`.`num_valid_votes`))) AS `9 - Shalva Natelashvili`,
      sum(`raw`.`10 - Giorgi Targamadze`) AS `10 - Giorgi Targamadze count`,
      (100 * (sum(`raw`.`10 - Giorgi Targamadze`) / sum(`raw`.`num_valid_votes`))) AS `10 - Giorgi Targamadze`,
      sum(`raw`.`11 - Levan Chachua`) AS `11 - Levan Chachua count`,
      (100 * (sum(`raw`.`11 - Levan Chachua`) / sum(`raw`.`num_valid_votes`))) AS `11 - Levan Chachua`,
      sum(`raw`.`12 - Nestan Kirtadze`) AS `12 - Nestan Kirtadze count`,
      (100 * (sum(`raw`.`12 - Nestan Kirtadze`) / sum(`raw`.`num_valid_votes`))) AS `12 - Nestan Kirtadze`,
      sum(`raw`.`13 - Giorgi Chikhladze`) AS `13 - Giorgi Chikhladze count`,
      (100 * (sum(`raw`.`13 - Giorgi Chikhladze`) / sum(`raw`.`num_valid_votes`))) AS `13 - Giorgi Chikhladze`,
      sum(`raw`.`14 - Nino Burjanadze`) AS `14 - Nino Burjanadze count`,
      (100 * (sum(`raw`.`14 - Nino Burjanadze`) / sum(`raw`.`num_valid_votes`))) AS `14 - Nino Burjanadze`,
      sum(`raw`.`15 - Zurab Kharatishvili`) AS `15 - Zurab Kharatishvili count`,
      (100 * (sum(`raw`.`15 - Zurab Kharatishvili`) / sum(`raw`.`num_valid_votes`))) AS `15 - Zurab Kharatishvili`,
      sum(`raw`.`16 - Mikheil Saluashvili`) AS `16 - Mikheil Saluashvili count`,
      (100 * (sum(`raw`.`16 - Mikheil Saluashvili`) / sum(`raw`.`num_valid_votes`))) AS `16 - Mikheil Saluashvili`, 
      sum(`raw`.`17 - Kartlos Gharibashvili`) AS `17 - Kartlos Gharibashvili count`,
      (100 * (sum(`raw`.`17 - Kartlos Gharibashvili`) / sum(`raw`.`num_valid_votes`))) AS `17 - Kartlos Gharibashvili`,
      sum(`raw`.`18 - Mamuka Chokhonelidze`) AS `18 - Mamuka Chokhonelidze count`,
      (100 * (sum(`raw`.`18 - Mamuka Chokhonelidze`) / sum(`raw`.`num_valid_votes`))) AS `18 - Mamuka Chokhonelidze`,
      sum(`raw`.`19 - Avtandil Margiani`) AS `19 - Avtandil Margiani count`,
      (100 * (sum(`raw`.`19 - Avtandil Margiani`) / sum(`raw`.`num_valid_votes`))) AS `19 - Avtandil Margiani`,
      sum(`raw`.`20 - Nugzar Avaliani`) AS `20 - Nugzar Avaliani count`,
      (100 * (sum(`raw`.`20 - Nugzar Avaliani`) / sum(`raw`.`num_valid_votes`))) AS `20 - Nugzar Avaliani`,
      sum(`raw`.`21 - Mamuka Melikishvili`) AS `21 - Mamuka Melikishvili count`,
      (100 * (sum(`raw`.`21 - Mamuka Melikishvili`) / sum(`raw`.`num_valid_votes`))) AS `21 - Mamuka Melikishvili`,
      sum(`raw`.`22 - Teimuraz Mzhavia`) AS `22 - Teimuraz Mzhavia count`,
      (100 * (sum(`raw`.`22 - Teimuraz Mzhavia`) / sum(`raw`.`num_valid_votes`))) AS `22 - Teimuraz Mzhavia`,
      sum(`raw`.`41 - Giorgi Margvelashvili`) AS `41 - Giorgi Margvelashvili count`,
      (100 * (sum(`raw`.`41 - Giorgi Margvelashvili`) / sum(`raw`.`num_valid_votes`))) AS `41 - Giorgi Margvelashvili` 
      from ((((((((`president2013s` `raw` left join `president2013s - vpm 8-12>2` `vpm1` on(((`raw`.`region` = `vpm1`.`region`) and (`raw`.`district_id` = `vpm1`.`district_id`) and (`raw`.`precinct_id` = `vpm1`.`precinct_id`)))) left join `president2013s - vpm 12-17>2` `vpm2` on(((`raw`.`region` = `vpm2`.`region`) and (`raw`.`district_id` = `vpm2`.`district_id`) and (`raw`.`precinct_id` = `vpm2`.`precinct_id`)))) left join `president2013s - vpm 17-20>2` `vpm3` on(((`raw`.`region` = convert(`vpm3`.`region` using utf8)) and (`raw`.`district_id` = `vpm3`.`district_id`) and (`raw`.`precinct_id` = `vpm3`.`precinct_id`)))) left join `president2013s - invalid ballots 0-1` `invalid_ballots_01` on(((`raw`.`region` = `invalid_ballots_01`.`region`) and (`raw`.`district_id` = `invalid_ballots_01`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_01`.`precinct_id`)))) left join `president2013s - invalid ballots 1-3` `invalid_ballots_13` on(((`raw`.`region` = `invalid_ballots_13`.`region`) and (`raw`.`district_id` = `invalid_ballots_13`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_13`.`precinct_id`)))) left join `president2013s - invalid ballots 3-5` `invalid_ballots_35` on(((`raw`.`region` = `invalid_ballots_35`.`region`) and (`raw`.`district_id` = `invalid_ballots_35`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_35`.`precinct_id`)))) left join `president2013s - invalid ballots >5` `invalid_ballots_>5` on(((`raw`.`region` = `invalid_ballots_>5`.`region`) and (`raw`.`district_id` = `invalid_ballots_>5`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_>5`.`precinct_id`)))) join `president2013s_precinct_count_country` `precinct_count`)"



      execute "create view `president2013s - districts` as
      select `raw`.`region` AS `region`,
      `raw`.`district_id` AS `district_id`,
      `raw`.`district_name` AS `district_Name`,
      sum(`raw`.`num_possible_voters`) AS `possible voters`,
      sum(`raw`.`num_votes`) AS `total ballots cast`,
      sum(`raw`.`num_valid_votes`) AS `total valid ballots cast`,
      ifnull(sum(`invalid_ballots_01`.`num_invalid_ballots`),
      0) AS `num invalid ballots from 0-1%`,
      ifnull(sum(`invalid_ballots_13`.`num_invalid_ballots`),
      0) AS `num invalid ballots from 1-3%`,
      ifnull(sum(`invalid_ballots_35`.`num_invalid_ballots`),
      0) AS `num invalid ballots from 3-5%`,
      ifnull(sum(`invalid_ballots_>5`.`num_invalid_ballots`),
      0) AS `num invalid ballots >5%`,
      (100 * (sum(`raw`.`num_valid_votes`) / sum(`raw`.`num_possible_voters`))) AS `percent voters voting`,
      sum(`raw`.`logic_check_fail`) AS `num precincts logic fail`,
      (100 * (sum(`raw`.`logic_check_fail`) / count(0))) AS `percent precincts logic fail`,
      (sum(`raw`.`logic_check_difference`) / sum(`raw`.`logic_check_fail`)) AS `avg precinct logic fail difference`,
      sum(`raw`.`more_ballots_than_votes_flag`) AS `num precincts more ballots than votes`,
      (100 * (sum(`raw`.`more_ballots_than_votes_flag`) / count(0))) AS `percent precincts more ballots than votes`,
      (sum(`raw`.`more_ballots_than_votes`) / sum(`raw`.`more_ballots_than_votes_flag`)) AS `avg precinct difference more ballots than votes`,
      sum(`raw`.`more_votes_than_ballots_flag`) AS `num precincts more votes than ballots`,
      (100 * (sum(`raw`.`more_votes_than_ballots_flag`) / count(0))) AS `percent precincts more votes than ballots`,
      (sum(`raw`.`more_votes_than_ballots`) / sum(`raw`.`more_votes_than_ballots_flag`)) AS `avg precinct difference more votes than ballots`,
      sum(`raw`.`num_at_12`) AS `votes 8-12`,
      sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) AS `votes 12-17`,
      sum((`raw`.`num_votes` - `raw`.`num_at_17`)) AS `votes 17-20`,
      (sum(`raw`.`num_at_12`) / count(0)) AS `avg votes/precinct 8-12`,
      (sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) / count(0)) AS `avg votes/precinct 12-17`,
      (sum((`raw`.`num_votes` - `raw`.`num_at_17`)) / count(0)) AS `avg votes/precinct 17-20`,
      (sum(`raw`.`num_at_12`) / 240) AS `vpm 8-12`,
      (sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) / 180) AS `vpm 12-17`,
      (sum((`raw`.`num_votes` - `raw`.`num_at_17`)) / 300) AS `vpm 17-20`,
      ((sum(`raw`.`num_at_12`) / 240) / count(0)) AS `avg vpm/precinct 8-12`,
      ((sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) / 180) / count(0)) AS `avg vpm/precinct 12-17`,
      ((sum((`raw`.`num_votes` - `raw`.`num_at_17`)) / 200) / count(0)) AS `avg vpm/precinct 17-20`,
      ifnull(sum(`vpm1`.`vpm > 2`),
      0) AS `num precincts vpm 8-12 > 2`,
      ifnull(sum(`vpm2`.`vpm > 2`),
      0) AS `num precincts vpm 12-17 > 2`,
      ifnull(sum(`vpm3`.`vpm > 2`),
      0) AS `num precincts vpm 17-20 > 2`,
      ((ifnull(sum(`vpm1`.`vpm > 2`),
      0) + ifnull(sum(`vpm2`.`vpm > 2`),
      0)) + ifnull(sum(`vpm3`.`vpm > 2`),
      0)) AS `num precincts vpm > 2`,
      `precinct_count`.`num_precincts` AS `num_precincts_possible`,
      count(`raw`.`precinct_id`) AS `num_precincts_reported_number`,
      ((100 * count(`raw`.`precinct_id`)) / `precinct_count`.`num_precincts`) AS `num_precincts_reported_percent`,
      sum(`raw`.`1 - Tamaz Bibiluri`) AS `1 - Tamaz Bibiluri count`,
      (100 * (sum(`raw`.`1 - Tamaz Bibiluri`) / sum(`raw`.`num_valid_votes`))) AS `1 - Tamaz Bibiluri`,
      sum(`raw`.`2 - Giorgi Liluashvili`) AS `2 - Giorgi Liluashvili count`,
      (100 * (sum(`raw`.`2 - Giorgi Liluashvili`) / sum(`raw`.`num_valid_votes`))) AS `2 - Giorgi Liluashvili`,
      sum(`raw`.`3 - Sergo Javakhidze`) AS `3 - Sergo Javakhidze count`,
      (100 * (sum(`raw`.`3 - Sergo Javakhidze`) / sum(`raw`.`num_valid_votes`))) AS `3 - Sergo Javakhidze`,
      sum(`raw`.`4 - Koba Davitashvili`) AS `4 - Koba Davitashvili count`,
      (100 * (sum(`raw`.`4 - Koba Davitashvili`) / sum(`raw`.`num_valid_votes`))) AS `4 - Koba Davitashvili`,
      sum(`raw`.`5 - Davit Bakradze`) AS `5 - Davit Bakradze count`,
      (100 * (sum(`raw`.`5 - Davit Bakradze`) / sum(`raw`.`num_valid_votes`))) AS `5 - Davit Bakradze`,
      sum(`raw`.`6 - Akaki Asatiani`) AS `6 - Akaki Asatiani count`,
      (100 * (sum(`raw`.`6 - Akaki Asatiani`) / sum(`raw`.`num_valid_votes`))) AS `6 - Akaki Asatiani`,
      sum(`raw`.`7 - Nino Chanishvili`) AS `7 - Nino Chanishvili count`,
      (100 * (sum(`raw`.`7 - Nino Chanishvili`) / sum(`raw`.`num_valid_votes`))) AS `7 - Nino Chanishvili`,
      sum(`raw`.`8 - Teimuraz Bobokhidze`) AS `8 - Teimuraz Bobokhidze count`,
      (100 * (sum(`raw`.`8 - Teimuraz Bobokhidze`) / sum(`raw`.`num_valid_votes`))) AS `8 - Teimuraz Bobokhidze`,
      sum(`raw`.`9 - Shalva Natelashvili`) AS `9 - Shalva Natelashvili count`,
      (100 * (sum(`raw`.`9 - Shalva Natelashvili`) / sum(`raw`.`num_valid_votes`))) AS `9 - Shalva Natelashvili`,
      sum(`raw`.`10 - Giorgi Targamadze`) AS `10 - Giorgi Targamadze count`,
      (100 * (sum(`raw`.`10 - Giorgi Targamadze`) / sum(`raw`.`num_valid_votes`))) AS `10 - Giorgi Targamadze`,
      sum(`raw`.`11 - Levan Chachua`) AS `11 - Levan Chachua count`,
      (100 * (sum(`raw`.`11 - Levan Chachua`) / sum(`raw`.`num_valid_votes`))) AS `11 - Levan Chachua`,
      sum(`raw`.`12 - Nestan Kirtadze`) AS `12 - Nestan Kirtadze count`,
      (100 * (sum(`raw`.`12 - Nestan Kirtadze`) / sum(`raw`.`num_valid_votes`))) AS `12 - Nestan Kirtadze`,
      sum(`raw`.`13 - Giorgi Chikhladze`) AS `13 - Giorgi Chikhladze count`,
      (100 * (sum(`raw`.`13 - Giorgi Chikhladze`) / sum(`raw`.`num_valid_votes`))) AS `13 - Giorgi Chikhladze`,
      sum(`raw`.`14 - Nino Burjanadze`) AS `14 - Nino Burjanadze count`,
      (100 * (sum(`raw`.`14 - Nino Burjanadze`) / sum(`raw`.`num_valid_votes`))) AS `14 - Nino Burjanadze`,
      sum(`raw`.`15 - Zurab Kharatishvili`) AS `15 - Zurab Kharatishvili count`,
      (100 * (sum(`raw`.`15 - Zurab Kharatishvili`) / sum(`raw`.`num_valid_votes`))) AS `15 - Zurab Kharatishvili`,
      sum(`raw`.`16 - Mikheil Saluashvili`) AS `16 - Mikheil Saluashvili count`,
      (100 * (sum(`raw`.`16 - Mikheil Saluashvili`) / sum(`raw`.`num_valid_votes`))) AS `16 - Mikheil Saluashvili`,
      sum(`raw`.`17 - Kartlos Gharibashvili`) AS `17 - Kartlos Gharibashvili count`,
      (100 * (sum(`raw`.`17 - Kartlos Gharibashvili`) / sum(`raw`.`num_valid_votes`))) AS `17 - Kartlos Gharibashvili`,
      sum(`raw`.`18 - Mamuka Chokhonelidze`) AS `18 - Mamuka Chokhonelidze count`,
      (100 * (sum(`raw`.`18 - Mamuka Chokhonelidze`) / sum(`raw`.`num_valid_votes`))) AS `18 - Mamuka Chokhonelidze`,
      sum(`raw`.`19 - Avtandil Margiani`) AS `19 - Avtandil Margiani count`,
      (100 * (sum(`raw`.`19 - Avtandil Margiani`) / sum(`raw`.`num_valid_votes`))) AS `19 - Avtandil Margiani`,
      sum(`raw`.`20 - Nugzar Avaliani`) AS `20 - Nugzar Avaliani count`,
      (100 * (sum(`raw`.`20 - Nugzar Avaliani`) / sum(`raw`.`num_valid_votes`))) AS `20 - Nugzar Avaliani`,
      sum(`raw`.`21 - Mamuka Melikishvili`) AS `21 - Mamuka Melikishvili count`,
      (100 * (sum(`raw`.`21 - Mamuka Melikishvili`) / sum(`raw`.`num_valid_votes`))) AS `21 - Mamuka Melikishvili`,
      sum(`raw`.`22 - Teimuraz Mzhavia`) AS `22 - Teimuraz Mzhavia count`,
      (100 * (sum(`raw`.`22 - Teimuraz Mzhavia`) / sum(`raw`.`num_valid_votes`))) AS `22 - Teimuraz Mzhavia`,
      sum(`raw`.`41 - Giorgi Margvelashvili`) AS `41 - Giorgi Margvelashvili count`,
      (100 * (sum(`raw`.`41 - Giorgi Margvelashvili`) / sum(`raw`.`num_valid_votes`))) AS `41 - Giorgi Margvelashvili` 
      from ((((((((`president2013s` `raw` join `president2013s_precinct_count_district` `precinct_count` on((`raw`.`district_id` = `precinct_count`.`district_id`))) left join `president2013s - vpm 8-12>2` `vpm1` on(((`raw`.`region` = `vpm1`.`region`) and (`raw`.`district_id` = `vpm1`.`district_id`) and (`raw`.`precinct_id` = `vpm1`.`precinct_id`)))) left join `president2013s - vpm 12-17>2` `vpm2` on(((`raw`.`region` = `vpm2`.`region`) and (`raw`.`district_id` = `vpm2`.`district_id`) and (`raw`.`precinct_id` = `vpm2`.`precinct_id`)))) left join `president2013s - vpm 17-20>2` `vpm3` on(((`raw`.`region` = convert(`vpm3`.`region` using utf8)) and (`raw`.`district_id` = `vpm3`.`district_id`) and (`raw`.`precinct_id` = `vpm3`.`precinct_id`)))) left join `president2013s - invalid ballots 0-1` `invalid_ballots_01` on(((`raw`.`region` = `invalid_ballots_01`.`region`) and (`raw`.`district_id` = `invalid_ballots_01`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_01`.`precinct_id`)))) left join `president2013s - invalid ballots 1-3` `invalid_ballots_13` on(((`raw`.`region` = `invalid_ballots_13`.`region`) and (`raw`.`district_id` = `invalid_ballots_13`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_13`.`precinct_id`)))) left join `president2013s - invalid ballots 3-5` `invalid_ballots_35` on(((`raw`.`region` = `invalid_ballots_35`.`region`) and (`raw`.`district_id` = `invalid_ballots_35`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_35`.`precinct_id`)))) left join `president2013s - invalid ballots >5` `invalid_ballots_>5` on(((`raw`.`region` = `invalid_ballots_>5`.`region`) and (`raw`.`district_id` = `invalid_ballots_>5`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_>5`.`precinct_id`)))) where (`raw`.`district_id` not between 1 and 10) group by `raw`.`region`,
      `raw`.`district_name`,
      `raw`.`district_id` union select `raw`.`region` AS `region`,
      999 AS `district_id`,
      `raw`.`region` AS `district_name`,
      sum(`raw`.`num_possible_voters`) AS `possible voters`,
      sum(`raw`.`num_votes`) AS `total ballots cast`,
      sum(`raw`.`num_valid_votes`) AS `total valid ballots cast`,
      ifnull(sum(`invalid_ballots_01`.`num_invalid_ballots`),
      0) AS `num invalid ballots from 0-1%`,
      ifnull(sum(`invalid_ballots_13`.`num_invalid_ballots`),
      0) AS `num invalid ballots from 1-3%`,
      ifnull(sum(`invalid_ballots_35`.`num_invalid_ballots`),
      0) AS `num invalid ballots from 3-5%`,
      ifnull(sum(`invalid_ballots_>5`.`num_invalid_ballots`),
      0) AS `num invalid ballots >5%`,
      (100 * (sum(`raw`.`num_valid_votes`) / sum(`raw`.`num_possible_voters`))) AS `percent voters voting`,
      sum(`raw`.`logic_check_fail`) AS `num precincts logic fail`,
      (100 * (sum(`raw`.`logic_check_fail`) / count(0))) AS `percent precincts logic fail`,
      (sum(`raw`.`logic_check_difference`) / sum(`raw`.`logic_check_fail`)) AS `avg precinct logic fail difference`,
      sum(`raw`.`more_ballots_than_votes_flag`) AS `num precincts more ballots than votes`,
      (100 * (sum(`raw`.`more_ballots_than_votes_flag`) / count(0))) AS `percent precincts more ballots than votes`,
      (sum(`raw`.`more_ballots_than_votes`) / sum(`raw`.`more_ballots_than_votes_flag`)) AS `avg precinct difference more ballots than votes`,
      sum(`raw`.`more_votes_than_ballots_flag`) AS `num precincts more votes than ballots`,
      (100 * (sum(`raw`.`more_votes_than_ballots_flag`) / count(0))) AS `percent precincts more votes than ballots`,
      (sum(`raw`.`more_votes_than_ballots`) / sum(`raw`.`more_votes_than_ballots_flag`)) AS `avg precinct difference more votes than ballots`,
      sum(`raw`.`num_at_12`) AS `votes 8-12`,
      sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) AS `votes 12-17`,
      sum((`raw`.`num_votes` - `raw`.`num_at_17`)) AS `votes 17-20`,
      (sum(`raw`.`num_at_12`) / count(0)) AS `avg votes/precinct 8-12`,
      (sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) / count(0)) AS `avg votes/precinct 12-17`,
      (sum((`raw`.`num_votes` - `raw`.`num_at_17`)) / count(0)) AS `avg votes/precinct 17-20`,
      (sum(`raw`.`num_at_12`) / 240) AS `vpm 8-12`,
      (sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) / 180) AS `vpm 12-17`,
      (sum((`raw`.`num_votes` - `raw`.`num_at_17`)) / 300) AS `vpm 17-20`,
      ((sum(`raw`.`num_at_12`) / 240) / count(0)) AS `avg vpm/precinct 8-12`,
      ((sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) / 180) / count(0)) AS `avg vpm/precinct 12-17`,
      ((sum((`raw`.`num_votes` - `raw`.`num_at_17`)) / 200) / count(0)) AS `avg vpm/precinct 17-20`,
      ifnull(sum(`vpm1`.`vpm > 2`),
      0) AS `num precincts vpm 8-12 > 2`,
      ifnull(sum(`vpm2`.`vpm > 2`),
      0) AS `num precincts vpm 12-17 > 2`,
      ifnull(sum(`vpm3`.`vpm > 2`),
      0) AS `num precincts vpm 17-20 > 2`,
      ((ifnull(sum(`vpm1`.`vpm > 2`),
      0) + ifnull(sum(`vpm2`.`vpm > 2`),
      0)) + ifnull(sum(`vpm3`.`vpm > 2`),
      0)) AS `num precincts vpm > 2`,
      `precinct_count`.`num_precincts` AS `num_precincts_possible`,
      count(`raw`.`precinct_id`) AS `num_precincts_reported_number`,
      ((100 * count(`raw`.`precinct_id`)) / `precinct_count`.`num_precincts`) AS `num_precincts_reported_percent`,
      sum(`raw`.`1 - Tamaz Bibiluri`) AS `1 - Tamaz Bibiluri count`,
      (100 * (sum(`raw`.`1 - Tamaz Bibiluri`) / sum(`raw`.`num_valid_votes`))) AS `1 - Tamaz Bibiluri`,
      sum(`raw`.`2 - Giorgi Liluashvili`) AS `2 - Giorgi Liluashvili count`,
      (100 * (sum(`raw`.`2 - Giorgi Liluashvili`) / sum(`raw`.`num_valid_votes`))) AS `2 - Giorgi Liluashvili`,
      sum(`raw`.`3 - Sergo Javakhidze`) AS `3 - Sergo Javakhidze count`,
      (100 * (sum(`raw`.`3 - Sergo Javakhidze`) / sum(`raw`.`num_valid_votes`))) AS `3 - Sergo Javakhidze`,
      sum(`raw`.`4 - Koba Davitashvili`) AS `4 - Koba Davitashvili count`,
      (100 * (sum(`raw`.`4 - Koba Davitashvili`) / sum(`raw`.`num_valid_votes`))) AS `4 - Koba Davitashvili`,
      sum(`raw`.`5 - Davit Bakradze`) AS `5 - Davit Bakradze count`,
      (100 * (sum(`raw`.`5 - Davit Bakradze`) / sum(`raw`.`num_valid_votes`))) AS `5 - Davit Bakradze`,
      sum(`raw`.`6 - Akaki Asatiani`) AS `6 - Akaki Asatiani count`,
      (100 * (sum(`raw`.`6 - Akaki Asatiani`) / sum(`raw`.`num_valid_votes`))) AS `6 - Akaki Asatiani`,
      sum(`raw`.`7 - Nino Chanishvili`) AS `7 - Nino Chanishvili count`,
      (100 * (sum(`raw`.`7 - Nino Chanishvili`) / sum(`raw`.`num_valid_votes`))) AS `7 - Nino Chanishvili`,
      sum(`raw`.`8 - Teimuraz Bobokhidze`) AS `8 - Teimuraz Bobokhidze count`,
      (100 * (sum(`raw`.`8 - Teimuraz Bobokhidze`) / sum(`raw`.`num_valid_votes`))) AS `8 - Teimuraz Bobokhidze`,
      sum(`raw`.`9 - Shalva Natelashvili`) AS `9 - Shalva Natelashvili count`,
      (100 * (sum(`raw`.`9 - Shalva Natelashvili`) / sum(`raw`.`num_valid_votes`))) AS `9 - Shalva Natelashvili`,
      sum(`raw`.`10 - Giorgi Targamadze`) AS `10 - Giorgi Targamadze count`,
      (100 * (sum(`raw`.`10 - Giorgi Targamadze`) / sum(`raw`.`num_valid_votes`))) AS `10 - Giorgi Targamadze`,
      sum(`raw`.`11 - Levan Chachua`) AS `11 - Levan Chachua count`,
      (100 * (sum(`raw`.`11 - Levan Chachua`) / sum(`raw`.`num_valid_votes`))) AS `11 - Levan Chachua`,
      sum(`raw`.`12 - Nestan Kirtadze`) AS `12 - Nestan Kirtadze count`,
      (100 * (sum(`raw`.`12 - Nestan Kirtadze`) / sum(`raw`.`num_valid_votes`))) AS `12 - Nestan Kirtadze`,
      sum(`raw`.`13 - Giorgi Chikhladze`) AS `13 - Giorgi Chikhladze count`,
      (100 * (sum(`raw`.`13 - Giorgi Chikhladze`) / sum(`raw`.`num_valid_votes`))) AS `13 - Giorgi Chikhladze`,
      sum(`raw`.`14 - Nino Burjanadze`) AS `14 - Nino Burjanadze count`,
      (100 * (sum(`raw`.`14 - Nino Burjanadze`) / sum(`raw`.`num_valid_votes`))) AS `14 - Nino Burjanadze`,
      sum(`raw`.`15 - Zurab Kharatishvili`) AS `15 - Zurab Kharatishvili count`,
      (100 * (sum(`raw`.`15 - Zurab Kharatishvili`) / sum(`raw`.`num_valid_votes`))) AS `15 - Zurab Kharatishvili`,
      sum(`raw`.`16 - Mikheil Saluashvili`) AS `16 - Mikheil Saluashvili count`,
      (100 * (sum(`raw`.`16 - Mikheil Saluashvili`) / sum(`raw`.`num_valid_votes`))) AS `16 - Mikheil Saluashvili`,
      sum(`raw`.`17 - Kartlos Gharibashvili`) AS `17 - Kartlos Gharibashvili count`,
      (100 * (sum(`raw`.`17 - Kartlos Gharibashvili`) / sum(`raw`.`num_valid_votes`))) AS `17 - Kartlos Gharibashvili`,
      sum(`raw`.`18 - Mamuka Chokhonelidze`) AS `18 - Mamuka Chokhonelidze count`,
      (100 * (sum(`raw`.`18 - Mamuka Chokhonelidze`) / sum(`raw`.`num_valid_votes`))) AS `18 - Mamuka Chokhonelidze`,
      sum(`raw`.`19 - Avtandil Margiani`) AS `19 - Avtandil Margiani count`,
      (100 * (sum(`raw`.`19 - Avtandil Margiani`) / sum(`raw`.`num_valid_votes`))) AS `19 - Avtandil Margiani`,
      sum(`raw`.`20 - Nugzar Avaliani`) AS `20 - Nugzar Avaliani count`,
      (100 * (sum(`raw`.`20 - Nugzar Avaliani`) / sum(`raw`.`num_valid_votes`))) AS `20 - Nugzar Avaliani`,
      sum(`raw`.`21 - Mamuka Melikishvili`) AS `21 - Mamuka Melikishvili count`,
      (100 * (sum(`raw`.`21 - Mamuka Melikishvili`) / sum(`raw`.`num_valid_votes`))) AS `21 - Mamuka Melikishvili`,
      sum(`raw`.`22 - Teimuraz Mzhavia`) AS `22 - Teimuraz Mzhavia count`,
      (100 * (sum(`raw`.`22 - Teimuraz Mzhavia`) / sum(`raw`.`num_valid_votes`))) AS `22 - Teimuraz Mzhavia`,
      sum(`raw`.`41 - Giorgi Margvelashvili`) AS `41 - Giorgi Margvelashvili count`,
      (100 * (sum(`raw`.`41 - Giorgi Margvelashvili`) / sum(`raw`.`num_valid_votes`))) AS `41 - Giorgi Margvelashvili` 
      from ((((((((`president2013s` `raw` join `president2013s_precinct_count_region` `precinct_count` on((`raw`.`region` = `precinct_count`.`region`))) left join `president2013s - vpm 8-12>2` `vpm1` on(((`raw`.`region` = `vpm1`.`region`) and (`raw`.`district_id` = `vpm1`.`district_id`) and (`raw`.`precinct_id` = `vpm1`.`precinct_id`)))) left join `president2013s - vpm 12-17>2` `vpm2` on(((`raw`.`region` = `vpm2`.`region`) and (`raw`.`district_id` = `vpm2`.`district_id`) and (`raw`.`precinct_id` = `vpm2`.`precinct_id`)))) left join `president2013s - vpm 17-20>2` `vpm3` on(((`raw`.`region` = convert(`vpm3`.`region` using utf8)) and (`raw`.`district_id` = `vpm3`.`district_id`) and (`raw`.`precinct_id` = `vpm3`.`precinct_id`)))) left join `president2013s - invalid ballots 0-1` `invalid_ballots_01` on(((`raw`.`region` = `invalid_ballots_01`.`region`) and (`raw`.`district_id` = `invalid_ballots_01`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_01`.`precinct_id`)))) left join `president2013s - invalid ballots 1-3` `invalid_ballots_13` on(((`raw`.`region` = `invalid_ballots_13`.`region`) and (`raw`.`district_id` = `invalid_ballots_13`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_13`.`precinct_id`)))) left join `president2013s - invalid ballots 3-5` `invalid_ballots_35` on(((`raw`.`region` = `invalid_ballots_35`.`region`) and (`raw`.`district_id` = `invalid_ballots_35`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_35`.`precinct_id`)))) left join `president2013s - invalid ballots >5` `invalid_ballots_>5` on(((`raw`.`region` = `invalid_ballots_>5`.`region`) and (`raw`.`district_id` = `invalid_ballots_>5`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_>5`.`precinct_id`)))) where (`raw`.`district_id` between 1 and 10) group by `raw`.`region`"




      execute "create view `president2013s - precincts` as
      select `raw`.`region` AS `region`,
      `raw`.`district_id` AS `district_id`,
      `raw`.`district_name` AS `district_Name`,
      `raw`.`precinct_id` AS `precinct_id`,
      concat(cast(`raw`.`district_id` as char charset utf8),
      '-',
      cast(`raw`.`precinct_id` as char charset utf8)) AS `precinct_name`,
      `raw`.`num_possible_voters` AS `possible voters`,
      `raw`.`num_votes` AS `total ballots cast`,
      `raw`.`num_valid_votes` AS `total valid ballots cast`,
      (100 * (`raw`.`num_invalid_votes` / `raw`.`num_votes`)) AS `percent invalid ballots`,
      (100 * (`raw`.`num_valid_votes` / `raw`.`num_possible_voters`)) AS `percent voters voting`,
      `raw`.`logic_check_fail` AS `logic_check_fail`,
      `raw`.`logic_check_difference` AS `logic_check_difference`,
      `raw`.`more_ballots_than_votes_flag` as `more_ballots_than_votes_flag`,
      `raw`.`more_ballots_than_votes` as `more_ballots_than_votes`,
      `raw`.`more_votes_than_ballots_flag` as `more_votes_than_ballots_flag`,
      `raw`.`more_votes_than_ballots` as `more_votes_than_ballots`,
      `raw`.`num_at_12` AS `votes 8-12`,
      (`raw`.`num_at_17` - `raw`.`num_at_12`) AS `votes 12-17`,
      (`raw`.`num_votes` - `raw`.`num_at_17`) AS `votes 17-20`,
      (`raw`.`num_at_12` / 240) AS `vpm 8-12`,
      ((`raw`.`num_at_17` - `raw`.`num_at_12`) / 300) AS `vpm 12-17`,
      ((`raw`.`num_votes` - `raw`.`num_at_17`) / 180) AS `vpm 17-20`,
      `raw`.`1 - Tamaz Bibiluri` AS `1 - Tamaz Bibiluri count`,
      (100 * (`raw`.`1 - Tamaz Bibiluri` / `raw`.`num_valid_votes`)) AS `1 - Tamaz Bibiluri`,
      `raw`.`2 - Giorgi Liluashvili` AS `2 - Giorgi Liluashvili count`,
      (100 * (`raw`.`2 - Giorgi Liluashvili` / `raw`.`num_valid_votes`)) AS `2 - Giorgi Liluashvili`,
      `raw`.`3 - Sergo Javakhidze` AS `3 - Sergo Javakhidze count`,
      (100 * (`raw`.`3 - Sergo Javakhidze` / `raw`.`num_valid_votes`)) AS `3 - Sergo Javakhidze`,
      `raw`.`4 - Koba Davitashvili` AS `4 - Koba Davitashvili count`,
      (100 * (`raw`.`4 - Koba Davitashvili` / `raw`.`num_valid_votes`)) AS `4 - Koba Davitashvili`,
      `raw`.`5 - Davit Bakradze` AS `5 - Davit Bakradze count`,
      (100 * (`raw`.`5 - Davit Bakradze` / `raw`.`num_valid_votes`)) AS `5 - Davit Bakradze`,
      `raw`.`6 - Akaki Asatiani` AS `6 - Akaki Asatiani count`,
      (100 * (`raw`.`6 - Akaki Asatiani` / `raw`.`num_valid_votes`)) AS `6 - Akaki Asatiani`,
      `raw`.`7 - Nino Chanishvili` AS `7 - Nino Chanishvili count`,
      (100 * (`raw`.`7 - Nino Chanishvili` / `raw`.`num_valid_votes`)) AS `7 - Nino Chanishvili`,
      `raw`.`8 - Teimuraz Bobokhidze` AS `8 - Teimuraz Bobokhidze count`,
      (100 * (`raw`.`8 - Teimuraz Bobokhidze` / `raw`.`num_valid_votes`)) AS `8 - Teimuraz Bobokhidze`,
      `raw`.`9 - Shalva Natelashvili` AS `9 - Shalva Natelashvili count`,
      (100 * (`raw`.`9 - Shalva Natelashvili` / `raw`.`num_valid_votes`)) AS `9 - Shalva Natelashvili`,
      `raw`.`10 - Giorgi Targamadze` AS `10 - Giorgi Targamadze count`,
      (100 * (`raw`.`10 - Giorgi Targamadze` / `raw`.`num_valid_votes`)) AS `10 - Giorgi Targamadze`,
      `raw`.`11 - Levan Chachua` AS `11 - Levan Chachua count`,
      (100 * (`raw`.`11 - Levan Chachua` / `raw`.`num_valid_votes`)) AS `11 - Levan Chachua`,
      `raw`.`12 - Nestan Kirtadze` AS `12 - Nestan Kirtadze count`,
      (100 * (`raw`.`12 - Nestan Kirtadze` / `raw`.`num_valid_votes`)) AS `12 - Nestan Kirtadze`,
      `raw`.`13 - Giorgi Chikhladze` AS `13 - Giorgi Chikhladze count`,
      (100 * (`raw`.`13 - Giorgi Chikhladze` / `raw`.`num_valid_votes`)) AS `13 - Giorgi Chikhladze`,
      `raw`.`14 - Nino Burjanadze` AS `14 - Nino Burjanadze count`,
      (100 * (`raw`.`14 - Nino Burjanadze` / `raw`.`num_valid_votes`)) AS `14 - Nino Burjanadze`,
      `raw`.`15 - Zurab Kharatishvili` AS `15 - Zurab Kharatishvili count`,
      (100 * (`raw`.`15 - Zurab Kharatishvili` / `raw`.`num_valid_votes`)) AS `15 - Zurab Kharatishvili`,
      `raw`.`16 - Mikheil Saluashvili` AS `16 - Mikheil Saluashvili count`,
      (100 * (`raw`.`16 - Mikheil Saluashvili` / `raw`.`num_valid_votes`)) AS `16 - Mikheil Saluashvili`,
      `raw`.`17 - Kartlos Gharibashvili` AS `17 - Kartlos Gharibashvili count`,
      (100 * (`raw`.`17 - Kartlos Gharibashvili` / `raw`.`num_valid_votes`)) AS `17 - Kartlos Gharibashvili`,
      `raw`.`18 - Mamuka Chokhonelidze` AS `18 - Mamuka Chokhonelidze count`,
      (100 * (`raw`.`18 - Mamuka Chokhonelidze` / `raw`.`num_valid_votes`)) AS `18 - Mamuka Chokhonelidze`,
      `raw`.`19 - Avtandil Margiani` AS `19 - Avtandil Margiani count`,
      (100 * (`raw`.`19 - Avtandil Margiani` / `raw`.`num_valid_votes`)) AS `19 - Avtandil Margiani`,
      `raw`.`20 - Nugzar Avaliani` AS `20 - Nugzar Avaliani count`,
      (100 * (`raw`.`20 - Nugzar Avaliani` / `raw`.`num_valid_votes`)) AS `20 - Nugzar Avaliani`,
      `raw`.`21 - Mamuka Melikishvili` AS `21 - Mamuka Melikishvili count`,
      (100 * (`raw`.`21 - Mamuka Melikishvili` / `raw`.`num_valid_votes`)) AS `21 - Mamuka Melikishvili`,
      `raw`.`22 - Teimuraz Mzhavia` AS `22 - Teimuraz Mzhavia count`,
      (100 * (`raw`.`22 - Teimuraz Mzhavia` / `raw`.`num_valid_votes`)) AS `22 - Teimuraz Mzhavia`,
      `raw`.`41 - Giorgi Margvelashvili` AS `41 - Giorgi Margvelashvili count`,
      (100 * (`raw`.`41 - Giorgi Margvelashvili` / `raw`.`num_valid_votes`)) AS `41 - Giorgi Margvelashvili` 
      from `president2013s` `raw` where (`raw`.`district_id` not between 1 and 10)"




      execute "create view `president2013s - region` as
      select `raw`.`region` AS `region`,
      sum(`raw`.`num_possible_voters`) AS `possible voters`,
      sum(`raw`.`num_votes`) AS `total ballots cast`,
      sum(`raw`.`num_valid_votes`) AS `total valid ballots cast`,
      ifnull(sum(`invalid_ballots_01`.`num_invalid_ballots`),
      0) AS `num invalid ballots from 0-1%`,
      ifnull(sum(`invalid_ballots_13`.`num_invalid_ballots`),
      0) AS `num invalid ballots from 1-3%`,
      ifnull(sum(`invalid_ballots_35`.`num_invalid_ballots`),
      0) AS `num invalid ballots from 3-5%`,
      ifnull(sum(`invalid_ballots_>5`.`num_invalid_ballots`),
      0) AS `num invalid ballots >5%`,
      (100 * (sum(`raw`.`num_valid_votes`) / sum(`raw`.`num_possible_voters`))) AS `percent voters voting`,
      sum(`raw`.`logic_check_fail`) AS `num precincts logic fail`,
      (100 * (sum(`raw`.`logic_check_fail`) / count(0))) AS `percent precincts logic fail`,
      (sum(`raw`.`logic_check_difference`) / sum(`raw`.`logic_check_fail`)) AS `avg precinct logic fail difference`,
      sum(`raw`.`more_ballots_than_votes_flag`) AS `num precincts more ballots than votes`,
      (100 * (sum(`raw`.`more_ballots_than_votes_flag`) / count(0))) AS `percent precincts more ballots than votes`,
      (sum(`raw`.`more_ballots_than_votes`) / sum(`raw`.`more_ballots_than_votes_flag`)) AS `avg precinct difference more ballots than votes`,
      sum(`raw`.`more_votes_than_ballots_flag`) AS `num precincts more votes than ballots`,
      (100 * (sum(`raw`.`more_votes_than_ballots_flag`) / count(0))) AS `percent precincts more votes than ballots`,
      (sum(`raw`.`more_votes_than_ballots`) / sum(`raw`.`more_votes_than_ballots_flag`)) AS `avg precinct difference more votes than ballots`,
      sum(`raw`.`num_at_12`) AS `votes 8-12`,
      sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) AS `votes 12-17`,
      sum((`raw`.`num_votes` - `raw`.`num_at_17`)) AS `votes 17-20`,
      (sum(`raw`.`num_at_12`) / count(0)) AS `avg votes/precinct 8-12`,
      (sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) / count(0)) AS `avg votes/precinct 12-17`,
      (sum((`raw`.`num_votes` - `raw`.`num_at_17`)) / count(0)) AS `avg votes/precinct 17-20`,
      (sum(`raw`.`num_at_12`) / 240) AS `vpm 8-12`,
      (sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) / 180) AS `vpm 12-17`,
      (sum((`raw`.`num_votes` - `raw`.`num_at_17`)) / 300) AS `vpm 17-20`,
      ((sum(`raw`.`num_at_12`) / 240) / count(0)) AS `avg vpm/precinct 8-12`,
      ((sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) / 180) / count(0)) AS `avg vpm/precinct 12-17`,
      ((sum((`raw`.`num_votes` - `raw`.`num_at_17`)) / 200) / count(0)) AS `avg vpm/precinct 17-20`,
      ifnull(sum(`vpm1`.`vpm > 2`),
      0) AS `num precincts vpm 8-12 > 2`,
      ifnull(sum(`vpm2`.`vpm > 2`),
      0) AS `num precincts vpm 12-17 > 2`,
      ifnull(sum(`vpm3`.`vpm > 2`),
      0) AS `num precincts vpm 17-20 > 2`,
      ((ifnull(sum(`vpm1`.`vpm > 2`),
      0) + ifnull(sum(`vpm2`.`vpm > 2`),
      0)) + ifnull(sum(`vpm3`.`vpm > 2`),
      0)) AS `num precincts vpm > 2`,
      `precinct_count`.`num_precincts` AS `num_precincts_possible`,
      count(`raw`.`precinct_id`) AS `num_precincts_reported_number`,
      ((100 * count(`raw`.`precinct_id`)) / `precinct_count`.`num_precincts`) AS `num_precincts_reported_percent`,
      sum(`raw`.`1 - Tamaz Bibiluri`) AS `1 - Tamaz Bibiluri count`,
      (100 * (sum(`raw`.`1 - Tamaz Bibiluri`) / sum(`raw`.`num_valid_votes`))) AS `1 - Tamaz Bibiluri`,
      sum(`raw`.`2 - Giorgi Liluashvili`) AS `2 - Giorgi Liluashvili count`,
      (100 * (sum(`raw`.`2 - Giorgi Liluashvili`) / sum(`raw`.`num_valid_votes`))) AS `2 - Giorgi Liluashvili`,
      sum(`raw`.`3 - Sergo Javakhidze`) AS `3 - Sergo Javakhidze count`,
      (100 * (sum(`raw`.`3 - Sergo Javakhidze`) / sum(`raw`.`num_valid_votes`))) AS `3 - Sergo Javakhidze`,
      sum(`raw`.`4 - Koba Davitashvili`) AS `4 - Koba Davitashvili count`,
      (100 * (sum(`raw`.`4 - Koba Davitashvili`) / sum(`raw`.`num_valid_votes`))) AS `4 - Koba Davitashvili`,
      sum(`raw`.`5 - Davit Bakradze`) AS `5 - Davit Bakradze count`,
      (100 * (sum(`raw`.`5 - Davit Bakradze`) / sum(`raw`.`num_valid_votes`))) AS `5 - Davit Bakradze`,
      sum(`raw`.`6 - Akaki Asatiani`) AS `6 - Akaki Asatiani count`,
      (100 * (sum(`raw`.`6 - Akaki Asatiani`) / sum(`raw`.`num_valid_votes`))) AS `6 - Akaki Asatiani`,
      sum(`raw`.`7 - Nino Chanishvili`) AS `7 - Nino Chanishvili count`,
      (100 * (sum(`raw`.`7 - Nino Chanishvili`) / sum(`raw`.`num_valid_votes`))) AS `7 - Nino Chanishvili`,
      sum(`raw`.`8 - Teimuraz Bobokhidze`) AS `8 - Teimuraz Bobokhidze count`,
      (100 * (sum(`raw`.`8 - Teimuraz Bobokhidze`) / sum(`raw`.`num_valid_votes`))) AS `8 - Teimuraz Bobokhidze`,
      sum(`raw`.`9 - Shalva Natelashvili`) AS `9 - Shalva Natelashvili count`,
      (100 * (sum(`raw`.`9 - Shalva Natelashvili`) / sum(`raw`.`num_valid_votes`))) AS `9 - Shalva Natelashvili`,
      sum(`raw`.`10 - Giorgi Targamadze`) AS `10 - Giorgi Targamadze count`,
      (100 * (sum(`raw`.`10 - Giorgi Targamadze`) / sum(`raw`.`num_valid_votes`))) AS `10 - Giorgi Targamadze`,
      sum(`raw`.`11 - Levan Chachua`) AS `11 - Levan Chachua count`,
      (100 * (sum(`raw`.`11 - Levan Chachua`) / sum(`raw`.`num_valid_votes`))) AS `11 - Levan Chachua`,
      sum(`raw`.`12 - Nestan Kirtadze`) AS `12 - Nestan Kirtadze count`,
      (100 * (sum(`raw`.`12 - Nestan Kirtadze`) / sum(`raw`.`num_valid_votes`))) AS `12 - Nestan Kirtadze`,
      sum(`raw`.`13 - Giorgi Chikhladze`) AS `13 - Giorgi Chikhladze count`,
      (100 * (sum(`raw`.`13 - Giorgi Chikhladze`) / sum(`raw`.`num_valid_votes`))) AS `13 - Giorgi Chikhladze`,
      sum(`raw`.`14 - Nino Burjanadze`) AS `14 - Nino Burjanadze count`,
      (100 * (sum(`raw`.`14 - Nino Burjanadze`) / sum(`raw`.`num_valid_votes`))) AS `14 - Nino Burjanadze`,
      sum(`raw`.`15 - Zurab Kharatishvili`) AS `15 - Zurab Kharatishvili count`,
      (100 * (sum(`raw`.`15 - Zurab Kharatishvili`) / sum(`raw`.`num_valid_votes`))) AS `15 - Zurab Kharatishvili`,
      sum(`raw`.`16 - Mikheil Saluashvili`) AS `16 - Mikheil Saluashvili count`,
      (100 * (sum(`raw`.`16 - Mikheil Saluashvili`) / sum(`raw`.`num_valid_votes`))) AS `16 - Mikheil Saluashvili`,
      sum(`raw`.`17 - Kartlos Gharibashvili`) AS `17 - Kartlos Gharibashvili count`,
      (100 * (sum(`raw`.`17 - Kartlos Gharibashvili`) / sum(`raw`.`num_valid_votes`))) AS `17 - Kartlos Gharibashvili`,
      sum(`raw`.`18 - Mamuka Chokhonelidze`) AS `18 - Mamuka Chokhonelidze count`,
      (100 * (sum(`raw`.`18 - Mamuka Chokhonelidze`) / sum(`raw`.`num_valid_votes`))) AS `18 - Mamuka Chokhonelidze`,
      sum(`raw`.`19 - Avtandil Margiani`) AS `19 - Avtandil Margiani count`,
      (100 * (sum(`raw`.`19 - Avtandil Margiani`) / sum(`raw`.`num_valid_votes`))) AS `19 - Avtandil Margiani`,
      sum(`raw`.`20 - Nugzar Avaliani`) AS `20 - Nugzar Avaliani count`,
      (100 * (sum(`raw`.`20 - Nugzar Avaliani`) / sum(`raw`.`num_valid_votes`))) AS `20 - Nugzar Avaliani`,
      sum(`raw`.`21 - Mamuka Melikishvili`) AS `21 - Mamuka Melikishvili count`,
      (100 * (sum(`raw`.`21 - Mamuka Melikishvili`) / sum(`raw`.`num_valid_votes`))) AS `21 - Mamuka Melikishvili`,
      sum(`raw`.`22 - Teimuraz Mzhavia`) AS `22 - Teimuraz Mzhavia count`,
      (100 * (sum(`raw`.`22 - Teimuraz Mzhavia`) / sum(`raw`.`num_valid_votes`))) AS `22 - Teimuraz Mzhavia`,
      sum(`raw`.`41 - Giorgi Margvelashvili`) AS `41 - Giorgi Margvelashvili count`,
      (100 * (sum(`raw`.`41 - Giorgi Margvelashvili`) / sum(`raw`.`num_valid_votes`))) AS `41 - Giorgi Margvelashvili` 
      from ((((((((`president2013s` `raw` join `president2013s_precinct_count_region` `precinct_count` on((`raw`.`region` = `precinct_count`.`region`))) left join `president2013s - vpm 8-12>2` `vpm1` on(((`raw`.`region` = `vpm1`.`region`) and (`raw`.`district_id` = `vpm1`.`district_id`) and (`raw`.`precinct_id` = `vpm1`.`precinct_id`)))) left join `president2013s - vpm 12-17>2` `vpm2` on(((`raw`.`region` = `vpm2`.`region`) and (`raw`.`district_id` = `vpm2`.`district_id`) and (`raw`.`precinct_id` = `vpm2`.`precinct_id`)))) left join `president2013s - vpm 17-20>2` `vpm3` on(((`raw`.`region` = convert(`vpm3`.`region` using utf8)) and (`raw`.`district_id` = `vpm3`.`district_id`) and (`raw`.`precinct_id` = `vpm3`.`precinct_id`)))) left join `president2013s - invalid ballots 0-1` `invalid_ballots_01` on(((`raw`.`region` = `invalid_ballots_01`.`region`) and (`raw`.`district_id` = `invalid_ballots_01`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_01`.`precinct_id`)))) left join `president2013s - invalid ballots 1-3` `invalid_ballots_13` on(((`raw`.`region` = `invalid_ballots_13`.`region`) and (`raw`.`district_id` = `invalid_ballots_13`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_13`.`precinct_id`)))) left join `president2013s - invalid ballots 3-5` `invalid_ballots_35` on(((`raw`.`region` = `invalid_ballots_35`.`region`) and (`raw`.`district_id` = `invalid_ballots_35`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_35`.`precinct_id`)))) left join `president2013s - invalid ballots >5` `invalid_ballots_>5` on(((`raw`.`region` = `invalid_ballots_>5`.`region`) and (`raw`.`district_id` = `invalid_ballots_>5`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_>5`.`precinct_id`)))) group by `raw`.`region`"




      execute "create view `president2013s - tbilisi district` as
      select `raw`.`region` AS `region`,
      `raw`.`district_id` AS `district_id`,
      `raw`.`district_name` AS `district_Name`,
      sum(`raw`.`num_possible_voters`) AS `possible voters`,
      sum(`raw`.`num_votes`) AS `total ballots cast`,
      sum(`raw`.`num_valid_votes`) AS `total valid ballots cast`,
      ifnull(sum(`invalid_ballots_01`.`num_invalid_ballots`),
      0) AS `num invalid ballots from 0-1%`,
      ifnull(sum(`invalid_ballots_13`.`num_invalid_ballots`),
      0) AS `num invalid ballots from 1-3%`,
      ifnull(sum(`invalid_ballots_35`.`num_invalid_ballots`),
      0) AS `num invalid ballots from 3-5%`,
      ifnull(sum(`invalid_ballots_>5`.`num_invalid_ballots`),
      0) AS `num invalid ballots >5%`,
      (100 * (sum(`raw`.`num_valid_votes`) / sum(`raw`.`num_possible_voters`))) AS `percent voters voting`,
      sum(`raw`.`logic_check_fail`) AS `num precincts logic fail`,
      (100 * (sum(`raw`.`logic_check_fail`) / count(0))) AS `percent precincts logic fail`,
      (sum(`raw`.`logic_check_difference`) / sum(`raw`.`logic_check_fail`)) AS `avg precinct logic fail difference`,
      sum(`raw`.`more_ballots_than_votes_flag`) AS `num precincts more ballots than votes`,
      (100 * (sum(`raw`.`more_ballots_than_votes_flag`) / count(0))) AS `percent precincts more ballots than votes`,
      (sum(`raw`.`more_ballots_than_votes`) / sum(`raw`.`more_ballots_than_votes_flag`)) AS `avg precinct difference more ballots than votes`,
      sum(`raw`.`more_votes_than_ballots_flag`) AS `num precincts more votes than ballots`,
      (100 * (sum(`raw`.`more_votes_than_ballots_flag`) / count(0))) AS `percent precincts more votes than ballots`,
      (sum(`raw`.`more_votes_than_ballots`) / sum(`raw`.`more_votes_than_ballots_flag`)) AS `avg precinct difference more votes than ballots`,
      sum(`raw`.`num_at_12`) AS `votes 8-12`,
      sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) AS `votes 12-17`,
      sum((`raw`.`num_votes` - `raw`.`num_at_17`)) AS `votes 17-20`,
      (sum(`raw`.`num_at_12`) / count(0)) AS `avg votes/precinct 8-12`,
      (sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) / count(0)) AS `avg votes/precinct 12-17`,
      (sum((`raw`.`num_votes` - `raw`.`num_at_17`)) / count(0)) AS `avg votes/precinct 17-20`,
      (sum(`raw`.`num_at_12`) / 240) AS `vpm 8-12`,
      (sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) / 180) AS `vpm 12-17`,
      (sum((`raw`.`num_votes` - `raw`.`num_at_17`)) / 300) AS `vpm 17-20`,
      ((sum(`raw`.`num_at_12`) / 240) / count(0)) AS `avg vpm/precinct 8-12`,
      ((sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) / 180) / count(0)) AS `avg vpm/precinct 12-17`,
      ((sum((`raw`.`num_votes` - `raw`.`num_at_17`)) / 200) / count(0)) AS `avg vpm/precinct 17-20`,
      ifnull(sum(`vpm1`.`vpm > 2`),
      0) AS `num precincts vpm 8-12 > 2`,
      ifnull(sum(`vpm2`.`vpm > 2`),
      0) AS `num precincts vpm 12-17 > 2`,
      ifnull(sum(`vpm3`.`vpm > 2`),
      0) AS `num precincts vpm 17-20 > 2`,
      ((ifnull(sum(`vpm1`.`vpm > 2`),
      0) + ifnull(sum(`vpm2`.`vpm > 2`),
      0)) + ifnull(sum(`vpm3`.`vpm > 2`),
      0)) AS `num precincts vpm > 2`,
      `precinct_count`.`num_precincts` AS `num_precincts_possible`,
      count(`raw`.`precinct_id`) AS `num_precincts_reported_number`,
      ((100 * count(`raw`.`precinct_id`)) / `precinct_count`.`num_precincts`) AS `num_precincts_reported_percent`,
      sum(`raw`.`1 - Tamaz Bibiluri`) AS `1 - Tamaz Bibiluri count`,
      (100 * (sum(`raw`.`1 - Tamaz Bibiluri`) / sum(`raw`.`num_valid_votes`))) AS `1 - Tamaz Bibiluri`,
      sum(`raw`.`2 - Giorgi Liluashvili`) AS `2 - Giorgi Liluashvili count`,
      (100 * (sum(`raw`.`2 - Giorgi Liluashvili`) / sum(`raw`.`num_valid_votes`))) AS `2 - Giorgi Liluashvili`,
      sum(`raw`.`3 - Sergo Javakhidze`) AS `3 - Sergo Javakhidze count`,
      (100 * (sum(`raw`.`3 - Sergo Javakhidze`) / sum(`raw`.`num_valid_votes`))) AS `3 - Sergo Javakhidze`,
      sum(`raw`.`4 - Koba Davitashvili`) AS `4 - Koba Davitashvili count`,
      (100 * (sum(`raw`.`4 - Koba Davitashvili`) / sum(`raw`.`num_valid_votes`))) AS `4 - Koba Davitashvili`,
      sum(`raw`.`5 - Davit Bakradze`) AS `5 - Davit Bakradze count`,
      (100 * (sum(`raw`.`5 - Davit Bakradze`) / sum(`raw`.`num_valid_votes`))) AS `5 - Davit Bakradze`,
      sum(`raw`.`6 - Akaki Asatiani`) AS `6 - Akaki Asatiani count`,
      (100 * (sum(`raw`.`6 - Akaki Asatiani`) / sum(`raw`.`num_valid_votes`))) AS `6 - Akaki Asatiani`,
      sum(`raw`.`7 - Nino Chanishvili`) AS `7 - Nino Chanishvili count`,
      (100 * (sum(`raw`.`7 - Nino Chanishvili`) / sum(`raw`.`num_valid_votes`))) AS `7 - Nino Chanishvili`,
      sum(`raw`.`8 - Teimuraz Bobokhidze`) AS `8 - Teimuraz Bobokhidze count`,
      (100 * (sum(`raw`.`8 - Teimuraz Bobokhidze`) / sum(`raw`.`num_valid_votes`))) AS `8 - Teimuraz Bobokhidze`,
      sum(`raw`.`9 - Shalva Natelashvili`) AS `9 - Shalva Natelashvili count`,
      (100 * (sum(`raw`.`9 - Shalva Natelashvili`) / sum(`raw`.`num_valid_votes`))) AS `9 - Shalva Natelashvili`,
      sum(`raw`.`10 - Giorgi Targamadze`) AS `10 - Giorgi Targamadze count`,
      (100 * (sum(`raw`.`10 - Giorgi Targamadze`) / sum(`raw`.`num_valid_votes`))) AS `10 - Giorgi Targamadze`,
      sum(`raw`.`11 - Levan Chachua`) AS `11 - Levan Chachua count`,
      (100 * (sum(`raw`.`11 - Levan Chachua`) / sum(`raw`.`num_valid_votes`))) AS `11 - Levan Chachua`,
      sum(`raw`.`12 - Nestan Kirtadze`) AS `12 - Nestan Kirtadze count`,
      (100 * (sum(`raw`.`12 - Nestan Kirtadze`) / sum(`raw`.`num_valid_votes`))) AS `12 - Nestan Kirtadze`,
      sum(`raw`.`13 - Giorgi Chikhladze`) AS `13 - Giorgi Chikhladze count`,
      (100 * (sum(`raw`.`13 - Giorgi Chikhladze`) / sum(`raw`.`num_valid_votes`))) AS `13 - Giorgi Chikhladze`,
      sum(`raw`.`14 - Nino Burjanadze`) AS `14 - Nino Burjanadze count`,
      (100 * (sum(`raw`.`14 - Nino Burjanadze`) / sum(`raw`.`num_valid_votes`))) AS `14 - Nino Burjanadze`,
      sum(`raw`.`15 - Zurab Kharatishvili`) AS `15 - Zurab Kharatishvili count`,
      (100 * (sum(`raw`.`15 - Zurab Kharatishvili`) / sum(`raw`.`num_valid_votes`))) AS `15 - Zurab Kharatishvili`,
      sum(`raw`.`16 - Mikheil Saluashvili`) AS `16 - Mikheil Saluashvili count`,
      (100 * (sum(`raw`.`16 - Mikheil Saluashvili`) / sum(`raw`.`num_valid_votes`))) AS `16 - Mikheil Saluashvili`,
      sum(`raw`.`17 - Kartlos Gharibashvili`) AS `17 - Kartlos Gharibashvili count`,
      (100 * (sum(`raw`.`17 - Kartlos Gharibashvili`) / sum(`raw`.`num_valid_votes`))) AS `17 - Kartlos Gharibashvili`,
      sum(`raw`.`18 - Mamuka Chokhonelidze`) AS `18 - Mamuka Chokhonelidze count`,
      (100 * (sum(`raw`.`18 - Mamuka Chokhonelidze`) / sum(`raw`.`num_valid_votes`))) AS `18 - Mamuka Chokhonelidze`,
      sum(`raw`.`19 - Avtandil Margiani`) AS `19 - Avtandil Margiani count`,
      (100 * (sum(`raw`.`19 - Avtandil Margiani`) / sum(`raw`.`num_valid_votes`))) AS `19 - Avtandil Margiani`,
      sum(`raw`.`20 - Nugzar Avaliani`) AS `20 - Nugzar Avaliani count`,
      (100 * (sum(`raw`.`20 - Nugzar Avaliani`) / sum(`raw`.`num_valid_votes`))) AS `20 - Nugzar Avaliani`,
      sum(`raw`.`21 - Mamuka Melikishvili`) AS `21 - Mamuka Melikishvili count`,
      (100 * (sum(`raw`.`21 - Mamuka Melikishvili`) / sum(`raw`.`num_valid_votes`))) AS `21 - Mamuka Melikishvili`,
      sum(`raw`.`22 - Teimuraz Mzhavia`) AS `22 - Teimuraz Mzhavia count`,
      (100 * (sum(`raw`.`22 - Teimuraz Mzhavia`) / sum(`raw`.`num_valid_votes`))) AS `22 - Teimuraz Mzhavia`,
      sum(`raw`.`41 - Giorgi Margvelashvili`) AS `41 - Giorgi Margvelashvili count`,
      (100 * (sum(`raw`.`41 - Giorgi Margvelashvili`) / sum(`raw`.`num_valid_votes`))) AS `41 - Giorgi Margvelashvili` 
      from ((((((((`president2013s` `raw` join `president2013s_precinct_count_district` `precinct_count` on((`raw`.`district_id` = `precinct_count`.`district_id`))) left join `president2013s - vpm 8-12>2` `vpm1` on(((`raw`.`region` = `vpm1`.`region`) and (`raw`.`district_id` = `vpm1`.`district_id`) and (`raw`.`precinct_id` = `vpm1`.`precinct_id`)))) left join `president2013s - vpm 12-17>2` `vpm2` on(((`raw`.`region` = `vpm2`.`region`) and (`raw`.`district_id` = `vpm2`.`district_id`) and (`raw`.`precinct_id` = `vpm2`.`precinct_id`)))) left join `president2013s - vpm 17-20>2` `vpm3` on(((`raw`.`region` = convert(`vpm3`.`region` using utf8)) and (`raw`.`district_id` = `vpm3`.`district_id`) and (`raw`.`precinct_id` = `vpm3`.`precinct_id`)))) left join `president2013s - invalid ballots 0-1` `invalid_ballots_01` on(((`raw`.`region` = `invalid_ballots_01`.`region`) and (`raw`.`district_id` = `invalid_ballots_01`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_01`.`precinct_id`)))) left join `president2013s - invalid ballots 1-3` `invalid_ballots_13` on(((`raw`.`region` = `invalid_ballots_13`.`region`) and (`raw`.`district_id` = `invalid_ballots_13`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_13`.`precinct_id`)))) left join `president2013s - invalid ballots 3-5` `invalid_ballots_35` on(((`raw`.`region` = `invalid_ballots_35`.`region`) and (`raw`.`district_id` = `invalid_ballots_35`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_35`.`precinct_id`)))) left join `president2013s - invalid ballots >5` `invalid_ballots_>5` on(((`raw`.`region` = `invalid_ballots_>5`.`region`) and (`raw`.`district_id` = `invalid_ballots_>5`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_>5`.`precinct_id`)))) where (`raw`.`district_id` between 1 and 10) group by `raw`.`region`,
      `raw`.`district_name`,
      `raw`.`district_id`"



      execute "create view `president2013s - tbilisi precincts` as
      select `raw`.`region` AS `region`,
      `raw`.`district_id` AS `district_id`,
      `raw`.`district_name` AS `district_Name`,
      `raw`.`precinct_id` AS `precinct_id`,
      concat(cast(`raw`.`district_id` as char charset utf8),
      '-',
      cast(`raw`.`precinct_id` as char charset utf8)) AS `precinct_name`,
      `raw`.`num_possible_voters` AS `possible voters`,
      `raw`.`num_votes` AS `total ballots cast`,
      `raw`.`num_valid_votes` AS `total valid ballots cast`,
      (100 * (`raw`.`num_invalid_votes` / `raw`.`num_votes`)) AS `percent invalid ballots`,
      (100 * (`raw`.`num_valid_votes` / `raw`.`num_possible_voters`)) AS `percent voters voting`,
      `raw`.`logic_check_fail` AS `logic_check_fail`,
      `raw`.`logic_check_difference` AS `logic_check_difference`,
      `raw`.`more_ballots_than_votes_flag` as `more_ballots_than_votes_flag`,
      `raw`.`more_ballots_than_votes` as `more_ballots_than_votes`,
      `raw`.`more_votes_than_ballots_flag` as `more_votes_than_ballots_flag`,
      `raw`.`more_votes_than_ballots` as `more_votes_than_ballots`,
      `raw`.`num_at_12` AS `votes 8-12`,
      (`raw`.`num_at_17` - `raw`.`num_at_12`) AS `votes 12-17`,
      (`raw`.`num_votes` - `raw`.`num_at_17`) AS `votes 17-20`,
      (`raw`.`num_at_12` / 240) AS `vpm 8-12`,
      ((`raw`.`num_at_17` - `raw`.`num_at_12`) / 300) AS `vpm 12-17`,
      ((`raw`.`num_votes` - `raw`.`num_at_17`) / 180) AS `vpm 17-20`,
      `raw`.`1 - Tamaz Bibiluri` AS `1 - Tamaz Bibiluri count`,
      (100 * (`raw`.`1 - Tamaz Bibiluri` / `raw`.`num_valid_votes`)) AS `1 - Tamaz Bibiluri`,
      `raw`.`2 - Giorgi Liluashvili` AS `2 - Giorgi Liluashvili count`,
      (100 * (`raw`.`2 - Giorgi Liluashvili` / `raw`.`num_valid_votes`)) AS `2 - Giorgi Liluashvili`,
      `raw`.`3 - Sergo Javakhidze` AS `3 - Sergo Javakhidze count`,
      (100 * (`raw`.`3 - Sergo Javakhidze` / `raw`.`num_valid_votes`)) AS `3 - Sergo Javakhidze`,
      `raw`.`4 - Koba Davitashvili` AS `4 - Koba Davitashvili count`,
      (100 * (`raw`.`4 - Koba Davitashvili` / `raw`.`num_valid_votes`)) AS `4 - Koba Davitashvili`,
      `raw`.`5 - Davit Bakradze` AS `5 - Davit Bakradze count`,
      (100 * (`raw`.`5 - Davit Bakradze` / `raw`.`num_valid_votes`)) AS `5 - Davit Bakradze`,
      `raw`.`6 - Akaki Asatiani` AS `6 - Akaki Asatiani count`,
      (100 * (`raw`.`6 - Akaki Asatiani` / `raw`.`num_valid_votes`)) AS `6 - Akaki Asatiani`,
      `raw`.`7 - Nino Chanishvili` AS `7 - Nino Chanishvili count`,
      (100 * (`raw`.`7 - Nino Chanishvili` / `raw`.`num_valid_votes`)) AS `7 - Nino Chanishvili`,
      `raw`.`8 - Teimuraz Bobokhidze` AS `8 - Teimuraz Bobokhidze count`,
      (100 * (`raw`.`8 - Teimuraz Bobokhidze` / `raw`.`num_valid_votes`)) AS `8 - Teimuraz Bobokhidze`,
      `raw`.`9 - Shalva Natelashvili` AS `9 - Shalva Natelashvili count`,
      (100 * (`raw`.`9 - Shalva Natelashvili` / `raw`.`num_valid_votes`)) AS `9 - Shalva Natelashvili`,
      `raw`.`10 - Giorgi Targamadze` AS `10 - Giorgi Targamadze count`,
      (100 * (`raw`.`10 - Giorgi Targamadze` / `raw`.`num_valid_votes`)) AS `10 - Giorgi Targamadze`,
      `raw`.`11 - Levan Chachua` AS `11 - Levan Chachua count`,
      (100 * (`raw`.`11 - Levan Chachua` / `raw`.`num_valid_votes`)) AS `11 - Levan Chachua`,
      `raw`.`12 - Nestan Kirtadze` AS `12 - Nestan Kirtadze count`,
      (100 * (`raw`.`12 - Nestan Kirtadze` / `raw`.`num_valid_votes`)) AS `12 - Nestan Kirtadze`,
      `raw`.`13 - Giorgi Chikhladze` AS `13 - Giorgi Chikhladze count`,
      (100 * (`raw`.`13 - Giorgi Chikhladze` / `raw`.`num_valid_votes`)) AS `13 - Giorgi Chikhladze`,
      `raw`.`14 - Nino Burjanadze` AS `14 - Nino Burjanadze count`,
      (100 * (`raw`.`14 - Nino Burjanadze` / `raw`.`num_valid_votes`)) AS `14 - Nino Burjanadze`,
      `raw`.`15 - Zurab Kharatishvili` AS `15 - Zurab Kharatishvili count`,
      (100 * (`raw`.`15 - Zurab Kharatishvili` / `raw`.`num_valid_votes`)) AS `15 - Zurab Kharatishvili`,
      `raw`.`16 - Mikheil Saluashvili` AS `16 - Mikheil Saluashvili count`,
      (100 * (`raw`.`16 - Mikheil Saluashvili` / `raw`.`num_valid_votes`)) AS `16 - Mikheil Saluashvili`,
      `raw`.`17 - Kartlos Gharibashvili` AS `17 - Kartlos Gharibashvili count`,
      (100 * (`raw`.`17 - Kartlos Gharibashvili` / `raw`.`num_valid_votes`)) AS `17 - Kartlos Gharibashvili`,
      `raw`.`18 - Mamuka Chokhonelidze` AS `18 - Mamuka Chokhonelidze count`,
      (100 * (`raw`.`18 - Mamuka Chokhonelidze` / `raw`.`num_valid_votes`)) AS `18 - Mamuka Chokhonelidze`,
      `raw`.`19 - Avtandil Margiani` AS `19 - Avtandil Margiani count`,
      (100 * (`raw`.`19 - Avtandil Margiani` / `raw`.`num_valid_votes`)) AS `19 - Avtandil Margiani`,
      `raw`.`20 - Nugzar Avaliani` AS `20 - Nugzar Avaliani count`,
      (100 * (`raw`.`20 - Nugzar Avaliani` / `raw`.`num_valid_votes`)) AS `20 - Nugzar Avaliani`,
      `raw`.`21 - Mamuka Melikishvili` AS `21 - Mamuka Melikishvili count`,
      (100 * (`raw`.`21 - Mamuka Melikishvili` / `raw`.`num_valid_votes`)) AS `21 - Mamuka Melikishvili`,
      `raw`.`22 - Teimuraz Mzhavia` AS `22 - Teimuraz Mzhavia count`,
      (100 * (`raw`.`22 - Teimuraz Mzhavia` / `raw`.`num_valid_votes`)) AS `22 - Teimuraz Mzhavia`,
      `raw`.`41 - Giorgi Margvelashvili` AS `41 - Giorgi Margvelashvili count`,
      (100 * (`raw`.`41 - Giorgi Margvelashvili` / `raw`.`num_valid_votes`)) AS `41 - Giorgi Margvelashvili` 
      from `president2013s` `raw` where (`raw`.`district_id` between 1 and 10)"





      execute "create view `president2013s - csv` as
      (select 'Country' AS `shape`,
      'Georgia' AS `common_id`,
      'Georgia' AS `common_name`,
      `president2013s - country`.`total valid ballots cast` AS `Total Voter Turnout (#)`,
      `president2013s - country`.`percent voters voting` AS `Total Voter Turnout (%)`,
      `president2013s - country`.`num invalid ballots from 0-1%` AS `Number of Precincts with Invalid Ballots from 0-1%`,
      `president2013s - country`.`num invalid ballots from 1-3%` AS `Number of Precincts with Invalid Ballots from 1-3%`,
      `president2013s - country`.`num invalid ballots from 3-5%` AS `Number of Precincts with Invalid Ballots from 3-5%`,
      `president2013s - country`.`num invalid ballots >5%` AS `Number of Precincts with Invalid Ballots > 5%`,
      NULL AS `Invalid Ballots (%)`,
      `president2013s - country`.`num precincts more ballots than votes` AS `Precincts with More Ballots Than Votes (#)`,
      `president2013s - country`.`percent precincts more ballots than votes` AS `Precincts with More Ballots Than Votes (%)`,
      `president2013s - country`.`avg precinct difference more ballots than votes` AS `More Ballots Than Votes (Average)`, 
      NULL AS `More Ballots Than Votes (#)`,
      `president2013s - country`.`num precincts more votes than ballots` AS `Precincts with More Votes than Ballots (#)`,
      `president2013s - country`.`percent precincts more votes than ballots` AS `Precincts with More Votes than Ballots (%)`,
      `president2013s - country`.`avg precinct difference more votes than ballots` AS `More Votes than Ballots (Average)`, 
      NULL AS `More Votes than Ballots (#)`,
      NULL AS `Average votes per minute (08:00-12:00)`,
      NULL AS `Average votes per minute (12:00-17:00)`,
      NULL AS `Average votes per minute (17:00-20:00)`,
      `president2013s - country`.`num precincts vpm 8-12 > 2` AS `Number of Precincts with votes per minute > 2 (08:00-12:00)`,
      `president2013s - country`.`num precincts vpm 12-17 > 2` AS `Number of Precincts with votes per minute > 2 (12:00-17:00)`,
      `president2013s - country`.`num precincts vpm 17-20 > 2` AS `Number of Precincts with votes per minute > 2 (17:00-20:00)`,
      `president2013s - country`.`num precincts vpm > 2` AS `Number of Precincts with votes per minute > 2`,
      `president2013s - country`.`num_precincts_reported_number` AS `Precincts Reported (#)`,
      `president2013s - country`.`num_precincts_reported_percent` AS `Precincts Reported (%)`,
      `president2013s - country`.`1 - Tamaz Bibiluri` AS `Tamaz Bibiluri`,
      `president2013s - country`.`2 - Giorgi Liluashvili` AS `Giorgi Liluashvili`,
      `president2013s - country`.`3 - Sergo Javakhidze` AS `Sergo Javakhidze`,
      `president2013s - country`.`4 - Koba Davitashvili` AS `Koba Davitashvili`,
      `president2013s - country`.`5 - Davit Bakradze` AS `Davit Bakradze`,
      `president2013s - country`.`6 - Akaki Asatiani` AS `Akaki Asatiani`,
      `president2013s - country`.`7 - Nino Chanishvili` AS `Nino Chanishvili`,
      `president2013s - country`.`8 - Teimuraz Bobokhidze` AS `Teimuraz Bobokhidze`,
      `president2013s - country`.`9 - Shalva Natelashvili` AS `Shalva Natelashvili`,
      `president2013s - country`.`10 - Giorgi Targamadze` AS `Giorgi Targamadze`,
      `president2013s - country`.`11 - Levan Chachua` AS `Levan Chachua`,
      `president2013s - country`.`12 - Nestan Kirtadze` AS `Nestan Kirtadze`,
      `president2013s - country`.`13 - Giorgi Chikhladze` AS `Giorgi Chikhladze`,
      `president2013s - country`.`14 - Nino Burjanadze` AS `Nino Burjanadze`,
      `president2013s - country`.`15 - Zurab Kharatishvili` AS `Zurab Kharatishvili`,
      `president2013s - country`.`16 - Mikheil Saluashvili` AS `Mikheil Saluashvili`,
      `president2013s - country`.`17 - Kartlos Gharibashvili` AS `Kartlos Gharibashvili`,
      `president2013s - country`.`18 - Mamuka Chokhonelidze` AS `Mamuka Chokhonelidze`,
      `president2013s - country`.`19 - Avtandil Margiani` AS `Avtandil Margiani`,
      `president2013s - country`.`20 - Nugzar Avaliani` AS `Nugzar Avaliani`,
      `president2013s - country`.`21 - Mamuka Melikishvili` AS `Mamuka Melikishvili`,
      `president2013s - country`.`22 - Teimuraz Mzhavia` AS `Teimuraz Mzhavia`,
      `president2013s - country`.`41 - Giorgi Margvelashvili` AS `Giorgi Margvelashvili`
      from `president2013s - country`)
      union
      (select 'Region' AS `shape`,
      `president2013s - region`.`region` AS `common_id`,
      `president2013s - region`.`region` AS `common_name`,
      `president2013s - region`.`total valid ballots cast` AS `Total Voter Turnout (#)`,
      `president2013s - region`.`percent voters voting` AS `Total Voter Turnout (%)`,
      `president2013s - region`.`num invalid ballots from 0-1%` AS `Number of Precincts with Invalid Ballots from 0-1%`,
      `president2013s - region`.`num invalid ballots from 1-3%` AS `Number of Precincts with Invalid Ballots from 1-3%`,
      `president2013s - region`.`num invalid ballots from 3-5%` AS `Number of Precincts with Invalid Ballots from 3-5%`,
      `president2013s - region`.`num invalid ballots >5%` AS `Number of Precincts with Invalid Ballots > 5%`,
      NULL AS `Invalid Ballots (%)`,
      `president2013s - region`.`num precincts more ballots than votes` AS `Precincts with More Ballots Than Votes (#)`,
      `president2013s - region`.`percent precincts more ballots than votes` AS `Precincts with More Ballots Than Votes (%)`,
      `president2013s - region`.`avg precinct difference more ballots than votes` AS `More Ballots Than Votes (Average)`, 
      NULL AS `More Ballots Than Votes (#)`,
      `president2013s - region`.`num precincts more votes than ballots` AS `Precincts with More Votes than Ballots (#)`,
      `president2013s - region`.`percent precincts more votes than ballots` AS `Precincts with More Votes than Ballots (%)`,
      `president2013s - region`.`avg precinct difference more votes than ballots` AS `More Votes than Ballots (Average)`, 
      NULL AS `More Votes than Ballots (#)`,
      NULL AS `Average votes per minute (08:00-12:00)`,
      NULL AS `Average votes per minute (12:00-17:00)`,
      NULL AS `Average votes per minute (17:00-20:00)`,
      `president2013s - region`.`num precincts vpm 8-12 > 2` AS `Number of Precincts with votes per minute > 2 (08:00-12:00)`,
      `president2013s - region`.`num precincts vpm 12-17 > 2` AS `Number of Precincts with votes per minute > 2 (12:00-17:00)`,
      `president2013s - region`.`num precincts vpm 17-20 > 2` AS `Number of Precincts with votes per minute > 2 (17:00-20:00)`,
      `president2013s - region`.`num precincts vpm > 2` AS `Number of Precincts with votes per minute > 2`,
      `president2013s - region`.`num_precincts_reported_number` AS `Precincts Reported (#)`,
      `president2013s - region`.`num_precincts_reported_percent` AS `Precincts Reported (%)`,
      `president2013s - region`.`1 - Tamaz Bibiluri` AS `Tamaz Bibiluri`,
      `president2013s - region`.`2 - Giorgi Liluashvili` AS `Giorgi Liluashvili`,
      `president2013s - region`.`3 - Sergo Javakhidze` AS `Sergo Javakhidze`,
      `president2013s - region`.`4 - Koba Davitashvili` AS `Koba Davitashvili`,
      `president2013s - region`.`5 - Davit Bakradze` AS `Davit Bakradze`,
      `president2013s - region`.`6 - Akaki Asatiani` AS `Akaki Asatiani`,
      `president2013s - region`.`7 - Nino Chanishvili` AS `Nino Chanishvili`,
      `president2013s - region`.`8 - Teimuraz Bobokhidze` AS `Teimuraz Bobokhidze`,
      `president2013s - region`.`9 - Shalva Natelashvili` AS `Shalva Natelashvili`,
      `president2013s - region`.`10 - Giorgi Targamadze` AS `Giorgi Targamadze`,
      `president2013s - region`.`11 - Levan Chachua` AS `Levan Chachua`,
      `president2013s - region`.`12 - Nestan Kirtadze` AS `Nestan Kirtadze`,
      `president2013s - region`.`13 - Giorgi Chikhladze` AS `Giorgi Chikhladze`,
      `president2013s - region`.`14 - Nino Burjanadze` AS `Nino Burjanadze`,
      `president2013s - region`.`15 - Zurab Kharatishvili` AS `Zurab Kharatishvili`,
      `president2013s - region`.`16 - Mikheil Saluashvili` AS `Mikheil Saluashvili`,
      `president2013s - region`.`17 - Kartlos Gharibashvili` AS `Kartlos Gharibashvili`,
      `president2013s - region`.`18 - Mamuka Chokhonelidze` AS `Mamuka Chokhonelidze`,
      `president2013s - region`.`19 - Avtandil Margiani` AS `Avtandil Margiani`,
      `president2013s - region`.`20 - Nugzar Avaliani` AS `Nugzar Avaliani`,
      `president2013s - region`.`21 - Mamuka Melikishvili` AS `Mamuka Melikishvili`,
      `president2013s - region`.`22 - Teimuraz Mzhavia` AS `Teimuraz Mzhavia`,
      `president2013s - region`.`41 - Giorgi Margvelashvili` AS `Giorgi Margvelashvili`
      from `president2013s - region`)
      union
      (select 'District' AS `shape`,
      `president2013s - districts`.`district_id` AS `common_id`,
      `president2013s - districts`.`district_Name` AS `common_name`,
      `president2013s - districts`.`total valid ballots cast` AS `Total Voter Turnout (#)`,
      `president2013s - districts`.`percent voters voting` AS `Total Voter Turnout (%)`,
      `president2013s - districts`.`num invalid ballots from 0-1%` AS `Number of Precincts with Invalid Ballots from 0-1%`,
      `president2013s - districts`.`num invalid ballots from 1-3%` AS `Number of Precincts with Invalid Ballots from 1-3%`,
      `president2013s - districts`.`num invalid ballots from 3-5%` AS `Number of Precincts with Invalid Ballots from 3-5%`,
      `president2013s - districts`.`num invalid ballots >5%` AS `Number of Precincts with Invalid Ballots > 5%`,
      NULL AS `Invalid Ballots (%)`,
      `president2013s - districts`.`num precincts more ballots than votes` AS `Precincts with More Ballots Than Votes (#)`,
      `president2013s - districts`.`percent precincts more ballots than votes` AS `Precincts with More Ballots Than Votes (%)`,
      `president2013s - districts`.`avg precinct difference more ballots than votes` AS `More Ballots Than Votes (Average)`, 
      NULL AS `More Ballots Than Votes (#)`,
      `president2013s - districts`.`num precincts more votes than ballots` AS `Precincts with More Votes than Ballots (#)`,
      `president2013s - districts`.`percent precincts more votes than ballots` AS `Precincts with More Votes than Ballots (%)`,
      `president2013s - districts`.`avg precinct difference more votes than ballots` AS `More Votes than Ballots (Average)`, 
      NULL AS `More Votes than Ballots (#)`,
      NULL AS `Average votes per minute (08:00-12:00)`,
      NULL AS `Average votes per minute (12:00-17:00)`,
      NULL AS `Average votes per minute (17:00-20:00)`,
      `president2013s - districts`.`num precincts vpm 8-12 > 2` AS `Number of Precincts with votes per minute > 2 (08:00-12:00)`,
      `president2013s - districts`.`num precincts vpm 12-17 > 2` AS `Number of Precincts with votes per minute > 2 (12:00-17:00)`,
      `president2013s - districts`.`num precincts vpm 17-20 > 2` AS `Number of Precincts with votes per minute > 2 (17:00-20:00)`,
      `president2013s - districts`.`num precincts vpm > 2` AS `Number of Precincts with votes per minute > 2`,
      `president2013s - districts`.`num_precincts_reported_number` AS `Precincts Reported (#)`,
      `president2013s - districts`.`num_precincts_reported_percent` AS `Precincts Reported (%)`,
      `president2013s - districts`.`1 - Tamaz Bibiluri` AS `1 - Tamaz Bibiluri`,
      `president2013s - districts`.`2 - Giorgi Liluashvili` AS `Giorgi Liluashvili`,
      `president2013s - districts`.`3 - Sergo Javakhidze` AS `Sergo Javakhidze`,
      `president2013s - districts`.`4 - Koba Davitashvili` AS `Koba Davitashvili`,
      `president2013s - districts`.`5 - Davit Bakradze` AS `Davit Bakradze`,
      `president2013s - districts`.`6 - Akaki Asatiani` AS `Akaki Asatiani`,
      `president2013s - districts`.`7 - Nino Chanishvili` AS `Nino Chanishvili`,
      `president2013s - districts`.`8 - Teimuraz Bobokhidze` AS `Teimuraz Bobokhidze`,
      `president2013s - districts`.`9 - Shalva Natelashvili` AS `Shalva Natelashvili`,
      `president2013s - districts`.`10 - Giorgi Targamadze` AS `Giorgi Targamadze`,
      `president2013s - districts`.`11 - Levan Chachua` AS `Levan Chachua`,
      `president2013s - districts`.`12 - Nestan Kirtadze` AS `Nestan Kirtadze`,
      `president2013s - districts`.`13 - Giorgi Chikhladze` AS `Giorgi Chikhladze`,
      `president2013s - districts`.`14 - Nino Burjanadze` AS `Nino Burjanadze`,
      `president2013s - districts`.`15 - Zurab Kharatishvili` AS `Zurab Kharatishvili`,
      `president2013s - districts`.`16 - Mikheil Saluashvili` AS `Mikheil Saluashvili`,
      `president2013s - districts`.`17 - Kartlos Gharibashvili` AS `Kartlos Gharibashvili`,
      `president2013s - districts`.`18 - Mamuka Chokhonelidze` AS `Mamuka Chokhonelidze`,
      `president2013s - districts`.`19 - Avtandil Margiani` AS `Avtandil Margiani`,
      `president2013s - districts`.`20 - Nugzar Avaliani` AS `Nugzar Avaliani`,
      `president2013s - districts`.`21 - Mamuka Melikishvili` AS `Mamuka Melikishvili`,
      `president2013s - districts`.`22 - Teimuraz Mzhavia` AS `Teimuraz Mzhavia`,
      `president2013s - districts`.`41 - Giorgi Margvelashvili` AS `Giorgi Margvelashvili`
      from `president2013s - districts`)
      union
      (select 'Precinct' AS `shape`,
      `president2013s - precincts`.`precinct_id` AS `common_id`,
      `president2013s - precincts`.`precinct_name` AS `common_name`,
      `president2013s - precincts`.`total valid ballots cast` AS `Total Voter Turnout (#)`,
      `president2013s - precincts`.`percent voters voting` AS `Total Voter Turnout (%)`,
      NULL AS `Number of Precincts with Invalid Ballots from 0-1%`,
      NULL AS `Number of Precincts with Invalid Ballots from 1-3%`,
      NULL AS `Number of Precincts with Invalid Ballots from 3-5%`,
      NULL AS `Number of Precincts with Invalid Ballots > 5%`,
      `president2013s - precincts`.`percent invalid ballots` AS `Invalid Ballots (%)`,
      null AS `Precincts with More Ballots Than Votes (#)`,
      null AS `Precincts with More Ballots Than Votes (%)`,
      null AS `More Ballots Than Votes (Average)`, 
      `president2013s - precincts`.`more_ballots_than_votes` AS `More Ballots Than Votes (#)`,
      null AS `Precincts with More Votes than Ballots (#)`,
      null AS `Precincts with More Votes than Ballots (%)`,
      null AS `More Votes than Ballots (Average)`, 
      `president2013s - precincts`.`more_votes_than_ballots` AS `More Votes than Ballots (#)`,
      `president2013s - precincts`.`vpm 8-12` AS `Average votes per minute (08:00-12:00)`,
      `president2013s - precincts`.`vpm 12-17` AS `Average votes per minute (12:00-17:00)`,
      `president2013s - precincts`.`vpm 17-20` AS `Average votes per minute (17:00-20:00)`,
      NULL AS `Number of Precincts with votes per minute > 2 (08:00-12:00)`,
      NULL AS `Number of Precincts with votes per minute > 2 (12:00-17:00)`,
      NULL AS `Number of Precincts with votes per minute > 2 (17:00-20:00)`,
      NULL AS `Number of Precincts with votes per minute > 2`,
      NULL AS `Precincts Reported (#)`,
      NULL AS `Precincts Reported (%)`,
      `president2013s - precincts`.`1 - Tamaz Bibiluri` AS `Tamaz Bibiluri`,
      `president2013s - precincts`.`2 - Giorgi Liluashvili` AS `Giorgi Liluashvili`,
      `president2013s - precincts`.`3 - Sergo Javakhidze` AS `Sergo Javakhidze`,
      `president2013s - precincts`.`4 - Koba Davitashvili` AS `Koba Davitashvili`,
      `president2013s - precincts`.`5 - Davit Bakradze` AS `Davit Bakradze`,
      `president2013s - precincts`.`6 - Akaki Asatiani` AS `Akaki Asatiani`,
      `president2013s - precincts`.`7 - Nino Chanishvili` AS `Nino Chanishvili`,
      `president2013s - precincts`.`8 - Teimuraz Bobokhidze` AS `Teimuraz Bobokhidze`,
      `president2013s - precincts`.`9 - Shalva Natelashvili` AS `Shalva Natelashvili`,
      `president2013s - precincts`.`10 - Giorgi Targamadze` AS `Giorgi Targamadze`,
      `president2013s - precincts`.`11 - Levan Chachua` AS `Levan Chachua`,
      `president2013s - precincts`.`12 - Nestan Kirtadze` AS `Nestan Kirtadze`,
      `president2013s - precincts`.`13 - Giorgi Chikhladze` AS `Giorgi Chikhladze`,
      `president2013s - precincts`.`14 - Nino Burjanadze` AS `Nino Burjanadze`,
      `president2013s - precincts`.`15 - Zurab Kharatishvili` AS `Zurab Kharatishvili`,
      `president2013s - precincts`.`16 - Mikheil Saluashvili` AS `Mikheil Saluashvili`,
      `president2013s - precincts`.`17 - Kartlos Gharibashvili` AS `Kartlos Gharibashvili`,
      `president2013s - precincts`.`18 - Mamuka Chokhonelidze` AS `Mamuka Chokhonelidze`,
      `president2013s - precincts`.`19 - Avtandil Margiani` AS `Avtandil Margiani`,
      `president2013s - precincts`.`20 - Nugzar Avaliani` AS `Nugzar Avaliani`,
      `president2013s - precincts`.`21 - Mamuka Melikishvili` AS `Mamuka Melikishvili`,
      `president2013s - precincts`.`22 - Teimuraz Mzhavia` AS `Teimuraz Mzhavia`,
      `president2013s - precincts`.`41 - Giorgi Margvelashvili` AS `Giorgi Margvelashvili`
      from `president2013s - precincts`)
      union
      (select 'Tbilisi District' AS `shape`,
      `president2013s - tbilisi district`.`district_id` AS `common_id`,
      `president2013s - tbilisi district`.`district_Name` AS `common_name`,
      `president2013s - tbilisi district`.`total valid ballots cast` AS `Total Voter Turnout (#)`,
      `president2013s - tbilisi district`.`percent voters voting` AS `Total Voter Turnout (%)`,
      `president2013s - tbilisi district`.`num invalid ballots from 0-1%` AS `Number of Precincts with Invalid Ballots from 0-1%`,
      `president2013s - tbilisi district`.`num invalid ballots from 1-3%` AS `Number of Precincts with Invalid Ballots from 1-3%`,
      `president2013s - tbilisi district`.`num invalid ballots from 3-5%` AS `Number of Precincts with Invalid Ballots from 3-5%`,
      `president2013s - tbilisi district`.`num invalid ballots >5%` AS `Number of Precincts with Invalid Ballots > 5%`,
      NULL AS `Invalid Ballots (%)`,
      `president2013s - tbilisi district`.`num precincts more ballots than votes` AS `Precincts with More Ballots Than Votes (#)`,
      `president2013s - tbilisi district`.`percent precincts more ballots than votes` AS `Precincts with More Ballots Than Votes (%)`,
      `president2013s - tbilisi district`.`avg precinct difference more ballots than votes` AS `More Ballots Than Votes (Average)`, 
      NULL AS `More Ballots Than Votes (#)`,
      `president2013s - tbilisi district`.`num precincts more votes than ballots` AS `Precincts with More Votes than Ballots (#)`,
      `president2013s - tbilisi district`.`percent precincts more votes than ballots` AS `Precincts with More Votes than Ballots (%)`,
      `president2013s - tbilisi district`.`avg precinct difference more votes than ballots` AS `More Votes than Ballots (Average)`, 
      NULL AS `More Votes than Ballots (#)`,
      NULL AS `Average votes per minute (08:00-12:00)`,
      NULL AS `Average votes per minute (12:00-17:00)`,
      NULL AS `Average votes per minute (17:00-20:00)`,
      `president2013s - tbilisi district`.`num precincts vpm 8-12 > 2` AS `Number of Precincts with votes per minute > 2 (08:00-12:00)`,
      `president2013s - tbilisi district`.`num precincts vpm 12-17 > 2` AS `Number of Precincts with votes per minute > 2 (12:00-17:00)`,
      `president2013s - tbilisi district`.`num precincts vpm 17-20 > 2` AS `Number of Precincts with votes per minute > 2 (17:00-20:00)`,
      `president2013s - tbilisi district`.`num precincts vpm > 2` AS `Number of Precincts with votes per minute > 2`,
      `president2013s - tbilisi district`.`num_precincts_reported_number` AS `Precincts Reported (#)`,
      `president2013s - tbilisi district`.`num_precincts_reported_percent` AS `Precincts Reported (%)`,
      `president2013s - tbilisi district`.`1 - Tamaz Bibiluri` AS `Tamaz Bibiluri`,
      `president2013s - tbilisi district`.`2 - Giorgi Liluashvili` AS `Giorgi Liluashvili`,
      `president2013s - tbilisi district`.`3 - Sergo Javakhidze` AS `Sergo Javakhidze`,
      `president2013s - tbilisi district`.`4 - Koba Davitashvili` AS `Koba Davitashvili`,
      `president2013s - tbilisi district`.`5 - Davit Bakradze` AS `Davit Bakradze`,
      `president2013s - tbilisi district`.`6 - Akaki Asatiani` AS `Akaki Asatiani`,
      `president2013s - tbilisi district`.`7 - Nino Chanishvili` AS `Nino Chanishvili`,
      `president2013s - tbilisi district`.`8 - Teimuraz Bobokhidze` AS `Teimuraz Bobokhidze`,
      `president2013s - tbilisi district`.`9 - Shalva Natelashvili` AS `Shalva Natelashvili`,
      `president2013s - tbilisi district`.`10 - Giorgi Targamadze` AS `Giorgi Targamadze`,
      `president2013s - tbilisi district`.`11 - Levan Chachua` AS `Levan Chachua`,
      `president2013s - tbilisi district`.`12 - Nestan Kirtadze` AS `Nestan Kirtadze`,
      `president2013s - tbilisi district`.`13 - Giorgi Chikhladze` AS `Giorgi Chikhladze`,
      `president2013s - tbilisi district`.`14 - Nino Burjanadze` AS `Nino Burjanadze`,
      `president2013s - tbilisi district`.`15 - Zurab Kharatishvili` AS `Zurab Kharatishvili`,
      `president2013s - tbilisi district`.`16 - Mikheil Saluashvili` AS `Mikheil Saluashvili`,
      `president2013s - tbilisi district`.`17 - Kartlos Gharibashvili` AS `Kartlos Gharibashvili`,
      `president2013s - tbilisi district`.`18 - Mamuka Chokhonelidze` AS `Mamuka Chokhonelidze`,
      `president2013s - tbilisi district`.`19 - Avtandil Margiani` AS `Avtandil Margiani`,
      `president2013s - tbilisi district`.`20 - Nugzar Avaliani` AS `Nugzar Avaliani`,
      `president2013s - tbilisi district`.`21 - Mamuka Melikishvili` AS `Mamuka Melikishvili`,
      `president2013s - tbilisi district`.`22 - Teimuraz Mzhavia` AS `Teimuraz Mzhavia`,
      `president2013s - tbilisi district`.`41 - Giorgi Margvelashvili` AS `Giorgi Margvelashvili`
      from `president2013s - tbilisi district`)
      union
      (select 'Tbilisi Precinct' AS `shape`,
      `president2013s - tbilisi precincts`.`precinct_id` AS `common_id`,
      `president2013s - tbilisi precincts`.`precinct_name` AS `common_name`,
      `president2013s - tbilisi precincts`.`total valid ballots cast` AS `Total Voter Turnout (#)`,
      `president2013s - tbilisi precincts`.`percent voters voting` AS `Total Voter Turnout (%)`,
      NULL AS `Number of Precincts with Invalid Ballots from 0-1%`,
      NULL AS `Number of Precincts with Invalid Ballots from 1-3%`,
      NULL AS `Number of Precincts with Invalid Ballots from 3-5%`,
      NULL AS `Number of Precincts with Invalid Ballots > 5%`,
      `president2013s - tbilisi precincts`.`percent invalid ballots` AS `Invalid Ballots (%)`,
      null AS `Precincts with More Ballots Than Votes (#)`,
      null AS `Precincts with More Ballots Than Votes (%)`,
      null AS `More Ballots Than Votes (Average)`, 
      `president2013s - tbilisi precincts`.`more_ballots_than_votes` AS `More Ballots Than Votes (#)`,
      null AS `Precincts with More Votes than Ballots (#)`,
      null AS `Precincts with More Votes than Ballots (%)`,
      null AS `More Votes than Ballots (Average)`, 
      `president2013s - tbilisi precincts`.`more_votes_than_ballots` AS `More Votes than Ballots (#)`,
      `president2013s - tbilisi precincts`.`vpm 8-12` AS `Average votes per minute (08:00-12:00)`,
      `president2013s - tbilisi precincts`.`vpm 12-17` AS `Average votes per minute (12:00-17:00)`,
      `president2013s - tbilisi precincts`.`vpm 17-20` AS `Average votes per minute (17:00-20:00)`,
      NULL AS `Number of Precincts with votes per minute > 2 (08:00-12:00)`,
      NULL AS `Number of Precincts with votes per minute > 2 (12:00-17:00)`,
      NULL AS `Number of Precincts with votes per minute > 2 (17:00-20:00)`,
      NULL AS `Number of Precincts with votes per minute > 2`,
      NULL AS `Precincts Reported (#)`,
      NULL AS `Precincts Reported (%)`,
      `president2013s - tbilisi precincts`.`1 - Tamaz Bibiluri` AS `Tamaz Bibiluri`,
      `president2013s - tbilisi precincts`.`2 - Giorgi Liluashvili` AS `Giorgi Liluashvili`,
      `president2013s - tbilisi precincts`.`3 - Sergo Javakhidze` AS `Sergo Javakhidze`,
      `president2013s - tbilisi precincts`.`4 - Koba Davitashvili` AS `Koba Davitashvili`,
      `president2013s - tbilisi precincts`.`5 - Davit Bakradze` AS `Davit Bakradze`,
      `president2013s - tbilisi precincts`.`6 - Akaki Asatiani` AS `Akaki Asatiani`,
      `president2013s - tbilisi precincts`.`7 - Nino Chanishvili` AS `Nino Chanishvili`,
      `president2013s - tbilisi precincts`.`8 - Teimuraz Bobokhidze` AS `Teimuraz Bobokhidze`,
      `president2013s - tbilisi precincts`.`9 - Shalva Natelashvili` AS `Shalva Natelashvili`,
      `president2013s - tbilisi precincts`.`10 - Giorgi Targamadze` AS `Giorgi Targamadze`,
      `president2013s - tbilisi precincts`.`11 - Levan Chachua` AS `Levan Chachua`,
      `president2013s - tbilisi precincts`.`12 - Nestan Kirtadze` AS `Nestan Kirtadze`,
      `president2013s - tbilisi precincts`.`13 - Giorgi Chikhladze` AS `Giorgi Chikhladze`,
      `president2013s - tbilisi precincts`.`14 - Nino Burjanadze` AS `Nino Burjanadze`,
      `president2013s - tbilisi precincts`.`15 - Zurab Kharatishvili` AS `Zurab Kharatishvili`,
      `president2013s - tbilisi precincts`.`16 - Mikheil Saluashvili` AS `Mikheil Saluashvili`,
      `president2013s - tbilisi precincts`.`17 - Kartlos Gharibashvili` AS `Kartlos Gharibashvili`,
      `president2013s - tbilisi precincts`.`18 - Mamuka Chokhonelidze` AS `Mamuka Chokhonelidze`,
      `president2013s - tbilisi precincts`.`19 - Avtandil Margiani` AS `Avtandil Margiani`,
      `president2013s - tbilisi precincts`.`20 - Nugzar Avaliani` AS `Nugzar Avaliani`,
      `president2013s - tbilisi precincts`.`21 - Mamuka Melikishvili` AS `Mamuka Melikishvili`,
      `president2013s - tbilisi precincts`.`22 - Teimuraz Mzhavia` AS `Teimuraz Mzhavia`,
      `president2013s - tbilisi precincts`.`41 - Giorgi Margvelashvili` AS `Giorgi Margvelashvili`
      from `president2013s - tbilisi precincts`)"
  end

  def down
      execute "drop view if exists `president2013s - invalid ballots 0-1`"
      execute "drop view if exists `president2013s - invalid ballots 1-3`"
      execute "drop view if exists `president2013s - invalid ballots 3-5`"
      execute "drop view if exists `president2013s - invalid ballots >5`"
      execute "drop view if exists `president2013s - vpm 8-12>2`"
      execute "drop view if exists `president2013s - vpm 12-17>2`"
      execute "drop view if exists `president2013s - vpm 17-20>2`"
      execute "drop view if exists `president2013s - country`"
      execute "drop view if exists `president2013s - districts`"
      execute "drop view if exists `president2013s - precincts`"
      execute "drop view if exists `president2013s - region`"
      execute "drop view if exists `president2013s - tbilisi district`"
      execute "drop view if exists `president2013s - tbilisi precincts`"
      execute "drop view if exists `president2013s - csv`"
  end

end
